package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"encoding/json"

	materializationapi "github.com/calypr/loom/graphqlapi/materialization"
	"github.com/calypr/loom/graphqlapi/model"
	queryapi "github.com/calypr/loom/graphqlapi/query"
)

// RunFhirDataframe is the resolver for the runFhirDataframe field.
func (r *mutationResolver) RunFhirDataframe(ctx context.Context, input model.FhirDataframeInput, limit *int) (*model.FhirDataframeResult, error) {
	result, err := r.query.Run(ctx, input, limit)
	if err != nil {
		return nil, err
	}
	return &model.FhirDataframeResult{
		Columns:     cloneStrings(result.Columns),
		Rows:        graphqlRows(result.Rows),
		RowCount:    result.RowCount,
		Diagnostics: dataframeDiagnostics(result.Diagnostics),
	}, nil
}

// DataframeBuilderIntrospection is the resolver for the dataframeBuilderIntrospection field.
func (r *queryResolver) DataframeBuilderIntrospection(ctx context.Context, input model.DataframeBuilderIntrospectionInput) (*model.DataframeBuilderIntrospection, error) {
	includePivotOnlyFields := true
	if input.IncludePivotOnlyFields != nil {
		includePivotOnlyFields = *input.IncludePivotOnlyFields
	}
	resp, err := r.query.Introspect(ctx, queryapi.IntrospectionRequest{
		Project:                input.Project,
		RootResourceType:       input.RootResourceType,
		AuthResourcePaths:      input.AuthResourcePaths,
		IncludePivotOnlyFields: includePivotOnlyFields,
	})
	if err != nil {
		return nil, err
	}
	return &model.DataframeBuilderIntrospection{
		Project:           resp.Project,
		RootResourceType:  resp.RootResourceType,
		AuthResourcePaths: append([]string(nil), resp.AuthResourcePaths...),
		Root:              resourceHints(resp.Root),
		RelatedResources:  relatedResourceHints(resp.RelatedResources),
		Traversals:        traversalHints(resp.Traversals),
		Fields:            fieldHints(resp.Fields),
		PivotFields:       fieldHints(resp.PivotFields),
	}, nil
}

// DataframeMaterialization is the resolver for the dataframeMaterialization field.
func (r *queryResolver) DataframeMaterialization(ctx context.Context, id string) (*model.DataframeMaterialization, error) {
	value, err := r.materializations.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return materializationapi.Model(*value), nil
}

// DataframeRows is the resolver for the dataframeRows field.
func (r *queryResolver) DataframeRows(ctx context.Context, input model.DataframeRowsInput) (*model.DataframeRowConnection, error) {
	page, err := r.materializations.Rows(ctx, input)
	if err != nil {
		return nil, err
	}
	rows, err := json.Marshal(page.Rows)
	if err != nil {
		return nil, err
	}
	var cursor *string
	if page.NextCursor != "" {
		cursor = &page.NextCursor
	}
	return &model.DataframeRowConnection{
		Materialization: materializationapi.Model(page.Materialization),
		Columns:         append([]string(nil), page.Columns...), Rows: rows,
		PageInfo: &model.DataframePageInfo{HasNextPage: page.HasNext, EndCursor: cursor},
	}, nil
}

// DataframeAggregate is the resolver for the dataframeAggregate field.
func (r *queryResolver) DataframeAggregate(ctx context.Context, input model.DataframeAggregateInput) (*model.DataframeAggregateResult, error) {
	groupBy := append([]string(nil), input.GroupBy...)
	column := ""
	if input.Column != nil {
		column = *input.Column
	}
	result, err := r.materializations.Aggregate(ctx, input.MaterializationID, groupBy, input.Filters, input.Operation, column)
	if err != nil {
		return nil, err
	}
	return &model.DataframeAggregateResult{Materialization: materializationapi.Model(result.Materialization), Columns: result.Columns, Rows: materializationapi.AggregateRows(result.Rows)}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
