package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	dataframeapi "github.com/calypr/loom/graphqlapi/dataframe"
	"github.com/calypr/loom/graphqlapi/model"
)

// RunFhirDataframe is the resolver for the runFhirDataframe field.
func (r *mutationResolver) RunFhirDataframe(ctx context.Context, input model.FhirDataframeInput, limit *int) (*model.FhirDataframeResult, error) {
	result, err := r.service.Run(ctx, input, limit)
	if err != nil {
		return nil, err
	}
	return &model.FhirDataframeResult{
		Columns:     cloneStrings(result.Columns),
		Rows:        graphqlRows(result.Rows),
		RowCount:    result.RowCount,
		Diagnostics: dataframeDiagnostics(result.Diagnostics),
	}, nil
}

// DataframeBuilderIntrospection is the resolver for the dataframeBuilderIntrospection field.
func (r *queryResolver) DataframeBuilderIntrospection(ctx context.Context, input model.DataframeBuilderIntrospectionInput) (*model.DataframeBuilderIntrospection, error) {
	includePivotOnlyFields := true
	if input.IncludePivotOnlyFields != nil {
		includePivotOnlyFields = *input.IncludePivotOnlyFields
	}
	resp, err := r.service.Introspect(ctx, dataframeapi.IntrospectionRequest{
		Project:                input.Project,
		RootResourceType:       input.RootResourceType,
		AuthResourcePaths:      input.AuthResourcePaths,
		IncludePivotOnlyFields: includePivotOnlyFields,
	})
	if err != nil {
		return nil, err
	}
	return &model.DataframeBuilderIntrospection{
		Project:           resp.Project,
		RootResourceType:  resp.RootResourceType,
		AuthResourcePaths: append([]string(nil), resp.AuthResourcePaths...),
		Root:              resourceHints(resp.Root),
		RelatedResources:  relatedResourceHints(resp.RelatedResources),
		Traversals:        traversalHints(resp.Traversals),
		Fields:            fieldHints(resp.Fields),
		PivotFields:       fieldHints(resp.PivotFields),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
