package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/calypr/loom/generated/graphql/graph/executor"
	"github.com/calypr/loom/generated/graphql/graph/model"
	dataframeapi "github.com/calypr/loom/internal/api/graphql/graph/dataframe"
	dataframeerrors "github.com/calypr/loom/internal/dataframe/errors"
	"github.com/calypr/loom/internal/dataframe/recipe"
)

// RunFhirDataframe is the resolver for the runFhirDataframe field.
func (r *mutationResolver) RunFhirDataframe(ctx context.Context, input model.FhirDataframeInput, limit *int) (*model.FhirDataframeResult, error) {
	result, err := r.query.Run(ctx, input, limit)
	if err != nil {
		return nil, err
	}
	rows, err := graphqlRows(result.Rows)
	if err != nil {
		return nil, err
	}
	return &model.FhirDataframeResult{
		Columns:     cloneStrings(result.Columns),
		Rows:        rows,
		RowCount:    result.RowCount,
		Diagnostics: dataframeDiagnostics(result.Diagnostics),
	}, nil
}

// RunDataframeRecipe executes a registered recipe completely and returns all
// selected rows. This is intentionally separate from preview and from the
// streaming publication mutation; callers should use materialization for
// large production exports.
func (r *mutationResolver) RunDataframeRecipe(ctx context.Context, input model.RunDataframeRecipeInput) (*model.DataframeRecipeResult, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings.OutputNames = append([]string(nil), input.Outputs...)
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	result, err := r.recipeControl.Run(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return fullRecipeResult(recipePreviewView{plan: result.Plan, outputs: result.Outputs}, input.Name)
}

// ValidateDataframeRecipe is the resolver for the validateDataframeRecipe field.
func (r *mutationResolver) ValidateDataframeRecipe(ctx context.Context, input model.ValidateDataframeRecipeInput) (*model.DataframeRecipeValidation, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	validated, err := r.recipeControl.Validate(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	outputs := make([]*model.DataframeRecipeOutputValidation, 0, len(validated.Plan.Outputs))
	for _, output := range validated.Plan.Outputs {
		outputs = append(outputs, outputValidation(output))
	}
	return &model.DataframeRecipeValidation{Name: input.Name, RecipeDigest: validated.Plan.RecipeDigest, TranslationVersion: validated.Plan.TranslationVersion, Outputs: outputs}, nil
}

// PreviewDataframeRecipe is the resolver for the previewDataframeRecipe field.
func (r *mutationResolver) PreviewDataframeRecipe(ctx context.Context, input model.PreviewDataframeRecipeInput) (*model.DataframeRecipePreview, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if input.Limit != nil {
		if *input.Limit < 0 {
			return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeInvalidLimit, ""))
		}
		bindings.PreviewLimit = *input.Limit
	}
	bindings.OutputNames = append([]string(nil), input.Outputs...)
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	preview, err := r.recipeControl.Preview(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return previewResult(recipePreviewView{plan: preview.Plan, outputs: preview.Outputs}, input.Name)
}

// RegisterDataframeRecipeRevision is the resolver for the registerDataframeRecipeRevision field.
func (r *mutationResolver) RegisterDataframeRecipeRevision(ctx context.Context, input model.RegisterDataframeRecipeRevisionInput) (*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return nil, recipeGraphQLError(fmt.Errorf("recipe revision store is unavailable"))
	}
	if _, err := r.authorizeRecipeWrite(ctx, recipe.RuntimeBindings{Project: input.ProjectID}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	var bundle recipe.Bundle
	if err := json.Unmarshal(input.Recipe, &bundle); err != nil {
		return nil, recipeGraphQLError(err)
	}
	parent := ""
	if input.ParentDigest != nil {
		parent = *input.ParentDigest
	}
	value, err := r.recipeRevisions.Register(ctx, input.ProjectID, bundle, parent)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return recipeRevisionModel(value), nil
}

// ProjectDataframeDatasets is the resolver for the projectDataframeDatasets field.
func (r *queryResolver) ProjectDataframeDatasets(ctx context.Context, projectID string) ([]*model.DataframeMaterialization, error) {
	values, err := r.dataframes.ProjectDatasets(ctx, projectID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.DataframeMaterialization, 0, len(values))
	for _, value := range values {
		result = append(result, dataframeapi.Model(value))
	}
	return result, nil
}

// DataframeDataset is the resolver for the dataframeDataset field.
func (r *queryResolver) DataframeDataset(ctx context.Context, input model.DataframeDatasetInput) (*model.DataframeMaterialization, error) {
	value, err := r.dataframes.Dataset(ctx, input)
	if err != nil {
		return nil, err
	}
	return dataframeapi.Model(*value), nil
}

// DataframeRows is the resolver for the dataframeRows field.
func (r *queryResolver) DataframeRows(ctx context.Context, input model.DataframeRowsInput) (*model.DataframeRowConnection, error) {
	page, err := r.dataframes.Rows(ctx, input)
	if err != nil {
		return nil, err
	}
	rows, err := json.Marshal(page.Rows)
	if err != nil {
		return nil, dataframeerrors.Wrap(err, dataframeerrors.CodeOutputEncodingFailed, "")
	}
	var cursor *string
	if page.NextCursor != "" {
		cursor = &page.NextCursor
	}
	totalCount := int(page.TotalCount)
	return &model.DataframeRowConnection{
		Materialization: dataframeapi.Model(page.Materialization),
		Columns:         append([]string(nil), page.Columns...), Rows: rows, TotalCount: &totalCount,
		PageInfo: &model.DataframePageInfo{HasNextPage: page.HasNext, EndCursor: cursor},
	}, nil
}

// DataframeAggregate is the resolver for the dataframeAggregate field.
func (r *queryResolver) DataframeAggregate(ctx context.Context, input model.DataframeAggregateInput) (*model.DataframeAggregateResult, error) {
	result, err := r.dataframes.AggregateInput(ctx, input)
	if err != nil {
		return nil, err
	}
	rows, err := dataframeapi.AggregateRowsResult(result.Rows)
	if err != nil {
		return nil, dataframeerrors.Wrap(err, dataframeerrors.CodeOutputEncodingFailed, "")
	}
	return &model.DataframeAggregateResult{Materialization: dataframeapi.Model(result.Materialization), Columns: result.Columns, Rows: rows}, nil
}

// DataframeAggregations is the resolver for the dataframeAggregations field.
func (r *queryResolver) DataframeAggregations(ctx context.Context, input model.DataframeAggregationsInput) (*model.DataframeAggregationsResult, error) {
	result, err := r.dataframes.AggregationsInput(ctx, input)
	if err != nil {
		return nil, err
	}
	aggregations, err := dataframeapi.AggregationsJSON(result)
	if err != nil {
		return nil, dataframeerrors.Wrap(err, dataframeerrors.CodeOutputEncodingFailed, "")
	}
	return &model.DataframeAggregationsResult{Materialization: dataframeapi.Model(result.Materialization), Aggregations: aggregations}, nil
}

// DataframeRecipeExecution is the resolver for the dataframeRecipeExecution field.
func (r *queryResolver) DataframeRecipeExecution(ctx context.Context, id string) (*model.DataframeRecipeExecution, error) {
	if r.recipeExecutions == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	execution, err := r.recipeExecutions(ctx, id)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if execution == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeRecipeExecutionNotFound, ""))
	}
	return executionModel(*execution), nil
}

// DataframeRecipeRevision is the resolver for the dataframeRecipeRevision field.
func (r *queryResolver) DataframeRecipeRevision(ctx context.Context, projectID string, name string, digest string) (*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return nil, nil
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: projectID}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	value, err := r.recipeRevisions.Get(ctx, projectID, name, digest)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return recipeRevisionModel(value), nil
}

// DataframeRecipeRevisions is the resolver for the dataframeRecipeRevisions field.
func (r *queryResolver) DataframeRecipeRevisions(ctx context.Context, projectID string, name string) ([]*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return []*model.DataframeRecipeRevision{}, nil
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: projectID}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	values, err := r.recipeRevisions.List(ctx, projectID, name)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result := make([]*model.DataframeRecipeRevision, 0, len(values))
	for _, value := range values {
		result = append(result, recipeRevisionModel(value))
	}
	return result, nil
}

// ExplainDataframeRecipe is the resolver for the explainDataframeRecipe field.
func (r *queryResolver) ExplainDataframeRecipe(ctx context.Context, input model.ExplainDataframeRecipeInput) (*model.DataframeRecipeExplanation, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	explanation, err := r.recipeControl.Explain(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result := planExplanation(explanation, input.Name)
	physical, err := r.recipeControl.ExplainPhysical(ctx, input.Name, bindings, input.Live != nil && *input.Live)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result.Physical = physicalExplanation(physical)
	return result, nil
}

// PreflightDataframeRecipe is the resolver for the preflightDataframeRecipe field.
func (r *queryResolver) PreflightDataframeRecipe(ctx context.Context, input model.PreflightDataframeRecipeInput) (*model.DataframeRecipePreflight, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	plan, err := r.recipeControl.Resolve(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return preflightResult(plan, input.Name), nil
}

// FhirGraph is the resolver for the fhirGraph field.
func (r *queryResolver) FhirGraph(ctx context.Context, input model.FhirGraphQueryInput) (*model.FhirGraphQueryResult, error) {
	return r.resolveFHIRGraph(ctx, input)
}

// ExplainFhirGraph is the resolver for the explainFhirGraph field.
func (r *queryResolver) ExplainFhirGraph(ctx context.Context, input model.FhirGraphQueryInput, live *bool) (*model.FhirGraphQueryExplanation, error) {
	return r.resolveExplainFHIRGraph(ctx, input, live)
}

// Mutation returns executor.MutationResolver implementation.
func (r *Resolver) Mutation() executor.MutationResolver { return &mutationResolver{r} }

// Query returns executor.QueryResolver implementation.
func (r *Resolver) Query() executor.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
