package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/calypr/loom/generated/graphql/graph/executor"
	"github.com/calypr/loom/generated/graphql/graph/model"
	materializationapi "github.com/calypr/loom/internal/api/graphql/graph/materialization"
	queryapi "github.com/calypr/loom/internal/api/graphql/graph/query"
	"github.com/calypr/loom/internal/authscope"
	dataframeerrors "github.com/calypr/loom/internal/dataframe/errors"
	"github.com/calypr/loom/internal/dataframe/recipe"
	"github.com/calypr/loom/internal/dataset"
)

// RunFhirDataframe is the resolver for the runFhirDataframe field.
func (r *mutationResolver) RunFhirDataframe(ctx context.Context, input model.FhirDataframeInput, limit *int) (*model.FhirDataframeResult, error) {
	result, err := r.query.Run(ctx, input, limit)
	if err != nil {
		return nil, err
	}
	rows, err := graphqlRows(result.Rows)
	if err != nil {
		return nil, err
	}
	return &model.FhirDataframeResult{
		Columns:     cloneStrings(result.Columns),
		Rows:        rows,
		RowCount:    result.RowCount,
		Diagnostics: dataframeDiagnostics(result.Diagnostics),
	}, nil
}

// RunDataframeRecipe executes a registered recipe completely and returns all
// selected rows. This is intentionally separate from preview and from the
// streaming publication mutation; callers should use materialization for
// large production exports.
func (r *mutationResolver) RunDataframeRecipe(ctx context.Context, input model.RunDataframeRecipeInput) (*model.DataframeRecipeResult, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings.OutputNames = append([]string(nil), input.Outputs...)
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	result, err := r.recipeControl.Run(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return fullRecipeResult(recipePreviewView{plan: result.Plan, outputs: result.Outputs}, input.Name)
}

// ValidateDataframeRecipe is the resolver for the validateDataframeRecipe field.
func (r *mutationResolver) ValidateDataframeRecipe(ctx context.Context, input model.ValidateDataframeRecipeInput) (*model.DataframeRecipeValidation, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	validated, err := r.recipeControl.Validate(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	outputs := make([]*model.DataframeRecipeOutputValidation, 0, len(validated.Plan.Outputs))
	for _, output := range validated.Plan.Outputs {
		outputs = append(outputs, outputValidation(output))
	}
	return &model.DataframeRecipeValidation{Name: input.Name, RecipeDigest: validated.Plan.RecipeDigest, TranslationVersion: validated.Plan.TranslationVersion, Outputs: outputs}, nil
}

// PreviewDataframeRecipe is the resolver for the previewDataframeRecipe field.
func (r *mutationResolver) PreviewDataframeRecipe(ctx context.Context, input model.PreviewDataframeRecipeInput) (*model.DataframeRecipePreview, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if input.Limit != nil {
		if *input.Limit < 0 {
			return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeInvalidLimit, ""))
		}
		bindings.PreviewLimit = *input.Limit
	}
	bindings.OutputNames = append([]string(nil), input.Outputs...)
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	preview, err := r.recipeControl.Preview(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return previewResult(recipePreviewView{plan: preview.Plan, outputs: preview.Outputs}, input.Name)
}

// MaterializeDataframeRecipeBundle is the resolver for the materializeDataframeRecipeBundle field.
func (r *mutationResolver) MaterializeDataframeRecipeBundle(ctx context.Context, input model.MaterializeDataframeRecipeInput) (*model.DataframeRecipeExecution, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeWrite(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	if r.recipeMaterialize == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	execution, err := r.recipeMaterialize(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return executionModel(execution), nil
}

// StartDataframeMaterialization is the resolver for the startDataframeMaterialization field.
func (r *mutationResolver) StartDataframeMaterialization(ctx context.Context, input model.StartDataframeMaterializationInput) (*model.DataframeRecipeExecution, error) {
	selector := dataset.DataframeSelector{Recipe: input.Selector.Recipe, TranslationVersion: input.Selector.TranslationVersion, Output: input.Selector.Output}
	if !selector.Valid() || input.Project == "" || input.Generation == "" {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeInvalidSelector, ""))
	}
	bindings, err := r.authorizeRecipeWrite(ctx, recipe.RuntimeBindings{Project: input.Project, DatasetGeneration: input.Generation})
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if r.exactMaterializationStarter == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	execution, err := r.exactMaterializationStarter(ctx, selector, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return executionModel(execution), nil
}

// ActivateProjectRelease is the resolver for the activateProjectRelease field.
func (r *mutationResolver) ActivateProjectRelease(ctx context.Context, input model.ActivateProjectReleaseInput) (*model.ProjectRelease, error) {
	project, releaseID := strings.TrimSpace(input.Project), strings.TrimSpace(input.ReleaseID)
	if project == "" || releaseID == "" {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeInvalidRequest, ""))
	}
	bindings, err := r.authorizeRecipeWrite(ctx, recipe.RuntimeBindings{Project: project})
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if r.projectReleaseActivator == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	expected := ""
	if input.ExpectedActiveRevision != nil {
		expected = strings.TrimSpace(*input.ExpectedActiveRevision)
	}
	release, err := r.projectReleaseActivator(ctx, bindings.Project, releaseID, expected)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return &model.ProjectRelease{ID: release.ID, Project: release.Project, Generation: release.Generation, Revision: release.Revision, State: model.ProjectReleaseState(release.State)}, nil
}

// PromoteDataframeContract is the resolver for the promoteDataframeContract field.
func (r *mutationResolver) PromoteDataframeContract(ctx context.Context, input model.PromoteDataframeContractInput) (*model.DataframeContract, error) {
	recipeName, version := strings.TrimSpace(input.Recipe), strings.TrimSpace(input.TranslationVersion)
	if recipeName == "" || version == "" {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeInvalidSelector, ""))
	}
	if r.dataframeContractAuthorizer == nil {
		return nil, recipeGraphQLError(authscope.ErrForbidden)
	}
	if err := r.dataframeContractAuthorizer(ctx); err != nil {
		return nil, recipeGraphQLError(err)
	}
	if r.dataframeContractPromoter == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	contract, err := r.dataframeContractPromoter(ctx, recipeName, version)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return &model.DataframeContract{Recipe: contract.Recipe, TranslationVersion: contract.TranslationVersion, PromotedAt: contract.PromotedAt}, nil
}

// RegisterDataframeRecipeRevision is the resolver for the registerDataframeRecipeRevision field.
func (r *mutationResolver) RegisterDataframeRecipeRevision(ctx context.Context, input model.RegisterDataframeRecipeRevisionInput) (*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return nil, recipeGraphQLError(fmt.Errorf("recipe revision store is unavailable"))
	}
	if _, err := r.authorizeRecipeWrite(ctx, recipe.RuntimeBindings{Project: input.ProjectID}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	var bundle recipe.Bundle
	if err := json.Unmarshal(input.Recipe, &bundle); err != nil {
		return nil, recipeGraphQLError(err)
	}
	parent := ""
	if input.ParentDigest != nil {
		parent = *input.ParentDigest
	}
	value, err := r.recipeRevisions.Register(ctx, input.ProjectID, bundle, parent)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return recipeRevisionModel(value), nil
}

// ValidateDataframeRecipeBundle is the resolver for the validateDataframeRecipeBundle field.
func (r *mutationResolver) ValidateDataframeRecipeBundle(ctx context.Context, input model.DataframeRecipeBundleInput) (*model.DataframeRecipeValidation, error) {
	if r.recipeBundleControl == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	bundle, bindings, err := inlineBundleInput(input)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	plan, err := r.recipeBundleControl.ValidateBundle(ctx, bundle, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	outputs := make([]*model.DataframeRecipeOutputValidation, 0, len(plan.Outputs))
	for _, output := range plan.Outputs {
		outputs = append(outputs, outputValidation(output))
	}
	return &model.DataframeRecipeValidation{Name: bundle.Name, RecipeDigest: plan.RecipeDigest, TranslationVersion: plan.TranslationVersion, Outputs: outputs}, nil
}

// PreviewDataframeRecipeBundle is the resolver for the previewDataframeRecipeBundle field.
func (r *mutationResolver) PreviewDataframeRecipeBundle(ctx context.Context, input model.DataframeRecipeBundleInput) (*model.DataframeRecipePreview, error) {
	if r.recipeBundleControl == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	bundle, bindings, err := inlineBundleInput(input)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	preview, err := r.recipeBundleControl.PreviewBundle(ctx, bundle, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return previewResult(recipePreviewView{plan: preview.Plan, outputs: preview.Outputs}, bundle.Name)
}

// SaveProjectDataframeRecipeDraft is the resolver for the saveProjectDataframeRecipeDraft field.
func (r *mutationResolver) SaveProjectDataframeRecipeDraft(ctx context.Context, input model.SaveProjectDataframeRecipeDraftInput) (*model.DataframeProjectRecipeDraft, error) {
	if r.projectRecipeDrafts == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	bundle, err := bundleFromJSON(input.Recipe)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err := r.authorizeRecipeWrite(ctx, recipe.RuntimeBindings{Project: input.Project})
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	draft := recipe.RecipeDraft{Project: bindings.Project, Document: bundle}
	if input.BaseRevisionID != nil {
		draft.BaseRevisionID = *input.BaseRevisionID
	}
	if input.UpdatedBy != nil {
		draft.UpdatedBy = *input.UpdatedBy
	}
	saved, err := r.projectRecipeDrafts.SaveDraft(ctx, draft, int64(input.ExpectedVersion))
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return projectRecipeDraftModel(saved), nil
}

// PublishProjectDataframeRecipe is the resolver for the publishProjectDataframeRecipe field.
func (r *mutationResolver) PublishProjectDataframeRecipe(ctx context.Context, input model.PublishProjectDataframeRecipeInput) (*model.DataframeRecipeRevision, error) {
	if r.projectRecipePublisher == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	bindings, err := r.authorizeRecipeWrite(ctx, recipe.RuntimeBindings{Project: input.Project})
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	expected := int64(-1)
	if input.ExpectedDraftVersion != nil {
		expected = int64(*input.ExpectedDraftVersion)
	}
	revision, err := r.projectRecipePublisher.Publish(ctx, bindings.Project, expected, input.DatasetGeneration, input.Outputs)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return recipeRevisionModel(revision), nil
}

// DataframeBuilderProjectMap is the resolver for the dataframeBuilderProjectMap field.
func (r *queryResolver) DataframeBuilderProjectMap(ctx context.Context, input model.DataframeBuilderProjectMapInput) (*model.DataframeBuilderProjectMap, error) {
	includePivotOnlyFields := false
	if input.IncludePivotOnlyFields != nil {
		includePivotOnlyFields = *input.IncludePivotOnlyFields
	}
	resp, err := r.query.ProjectMap(ctx, queryapi.ProjectMapRequest{
		Project:                input.Project,
		AuthResourcePaths:      input.AuthResourcePaths,
		IncludePivotOnlyFields: includePivotOnlyFields,
	})
	if err != nil {
		return nil, err
	}
	resources := make([]*model.DataframeResourceHints, 0, len(resp.Resources))
	for _, resource := range resp.Resources {
		resources = append(resources, resourceHints(resource))
	}
	return &model.DataframeBuilderProjectMap{
		Project:          resp.Project,
		SourceGeneration: resp.SourceGeneration,
		Resources:        resources,
		Relationships:    traversalHints(resp.Relationships),
	}, nil
}

// DataframeBuilderIntrospection is the resolver for the dataframeBuilderIntrospection field.
func (r *queryResolver) DataframeBuilderIntrospection(ctx context.Context, input model.DataframeBuilderIntrospectionInput) (*model.DataframeBuilderIntrospection, error) {
	includePivotOnlyFields := true
	if input.IncludePivotOnlyFields != nil {
		includePivotOnlyFields = *input.IncludePivotOnlyFields
	}
	resp, err := r.query.Introspect(ctx, queryapi.IntrospectionRequest{
		Project:                input.Project,
		RootResourceType:       input.RootResourceType,
		AuthResourcePaths:      input.AuthResourcePaths,
		IncludePivotOnlyFields: includePivotOnlyFields,
	})
	if err != nil {
		return nil, err
	}
	return &model.DataframeBuilderIntrospection{
		Project:           resp.Project,
		RootResourceType:  resp.RootResourceType,
		AuthResourcePaths: append([]string(nil), resp.AuthResourcePaths...),
		Root:              resourceHints(resp.Root),
		RelatedResources:  relatedResourceHints(resp.RelatedResources),
		Traversals:        traversalHints(resp.Traversals),
		Fields:            fieldHints(resp.Fields),
		PivotFields:       fieldHints(resp.PivotFields),
	}, nil
}

// DataframeMaterialization is the resolver for the dataframeMaterialization field.
func (r *queryResolver) DataframeMaterialization(ctx context.Context, id string) (*model.DataframeMaterialization, error) {
	value, err := r.materializations.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return materializationapi.Model(*value), nil
}

// DataframeDatasets is the resolver for the dataframeDatasets field.
func (r *queryResolver) DataframeDatasets(ctx context.Context) ([]*model.DataframeMaterialization, error) {
	values, err := r.materializations.Datasets(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.DataframeMaterialization, 0, len(values))
	for _, value := range values {
		result = append(result, materializationapi.Model(value))
	}
	return result, nil
}

// ProjectDataframeDatasets is the resolver for the projectDataframeDatasets field.
func (r *queryResolver) ProjectDataframeDatasets(ctx context.Context, projectID string) ([]*model.DataframeMaterialization, error) {
	values, err := r.materializations.ProjectDatasets(ctx, projectID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.DataframeMaterialization, 0, len(values))
	for _, value := range values {
		result = append(result, materializationapi.Model(value))
	}
	return result, nil
}

// DataframeDataset is the resolver for the dataframeDataset field.
func (r *queryResolver) DataframeDataset(ctx context.Context, input model.DataframeDatasetInput) (*model.DataframeMaterialization, error) {
	value, err := r.materializations.Dataset(ctx, input)
	if err != nil {
		return nil, err
	}
	return materializationapi.Model(*value), nil
}

// DataframeRows is the resolver for the dataframeRows field.
func (r *queryResolver) DataframeRows(ctx context.Context, input model.DataframeRowsInput) (*model.DataframeRowConnection, error) {
	page, err := r.materializations.Rows(ctx, input)
	if err != nil {
		return nil, err
	}
	rows, err := json.Marshal(page.Rows)
	if err != nil {
		return nil, dataframeerrors.Wrap(err, dataframeerrors.CodeOutputEncodingFailed, "")
	}
	var cursor *string
	if page.NextCursor != "" {
		cursor = &page.NextCursor
	}
	totalCount := int(page.TotalCount)
	return &model.DataframeRowConnection{
		Materialization: materializationapi.Model(page.Materialization),
		Columns:         append([]string(nil), page.Columns...), Rows: rows, TotalCount: &totalCount,
		PageInfo: &model.DataframePageInfo{HasNextPage: page.HasNext, EndCursor: cursor},
	}, nil
}

// DataframeAggregate is the resolver for the dataframeAggregate field.
func (r *queryResolver) DataframeAggregate(ctx context.Context, input model.DataframeAggregateInput) (*model.DataframeAggregateResult, error) {
	result, err := r.materializations.AggregateInput(ctx, input)
	if err != nil {
		return nil, err
	}
	rows, err := materializationapi.AggregateRowsResult(result.Rows)
	if err != nil {
		return nil, dataframeerrors.Wrap(err, dataframeerrors.CodeOutputEncodingFailed, "")
	}
	return &model.DataframeAggregateResult{Materialization: materializationapi.Model(result.Materialization), Columns: result.Columns, Rows: rows}, nil
}

// DataframeAggregations is the resolver for the dataframeAggregations field.
func (r *queryResolver) DataframeAggregations(ctx context.Context, input model.DataframeAggregationsInput) (*model.DataframeAggregationsResult, error) {
	result, err := r.materializations.AggregationsInput(ctx, input)
	if err != nil {
		return nil, err
	}
	aggregations, err := materializationapi.AggregationsJSON(result)
	if err != nil {
		return nil, dataframeerrors.Wrap(err, dataframeerrors.CodeOutputEncodingFailed, "")
	}
	return &model.DataframeAggregationsResult{Materialization: materializationapi.FederatedMaterialization(result.Dataset), Aggregations: aggregations}, nil
}

// DataframeRecipeExecution is the resolver for the dataframeRecipeExecution field.
func (r *queryResolver) DataframeRecipeExecution(ctx context.Context, id string) (*model.DataframeRecipeExecution, error) {
	if r.recipeExecutions == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	execution, err := r.recipeExecutions(ctx, id)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if execution == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeRecipeExecutionNotFound, ""))
	}
	return executionModel(*execution), nil
}

// DataframeRecipeRevision is the resolver for the dataframeRecipeRevision field.
func (r *queryResolver) DataframeRecipeRevision(ctx context.Context, projectID string, name string, digest string) (*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return nil, nil
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: projectID}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	value, err := r.recipeRevisions.Get(ctx, projectID, name, digest)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return recipeRevisionModel(value), nil
}

// DataframeRecipeRevisions is the resolver for the dataframeRecipeRevisions field.
func (r *queryResolver) DataframeRecipeRevisions(ctx context.Context, projectID string, name string) ([]*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return []*model.DataframeRecipeRevision{}, nil
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: projectID}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	values, err := r.recipeRevisions.List(ctx, projectID, name)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result := make([]*model.DataframeRecipeRevision, 0, len(values))
	for _, value := range values {
		result = append(result, recipeRevisionModel(value))
	}
	return result, nil
}

// ProjectDataframeRecipeDraft is the resolver for the projectDataframeRecipeDraft field.
func (r *queryResolver) ProjectDataframeRecipeDraft(ctx context.Context, project string) (*model.DataframeProjectRecipeDraft, error) {
	project = strings.TrimSpace(project)
	if project == "" {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeProjectRequired, ""))
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: project}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	if r.projectRecipeDrafts != nil {
		if value, err := r.projectRecipeDrafts.GetDraft(ctx, project); err == nil {
			return projectRecipeDraftModel(value), nil
		} else if !errors.Is(err, recipe.ErrDraftNotFound) {
			return nil, recipeGraphQLError(err)
		}
	}
	if r.defaultRecipeBundle == nil {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeRecipeNotFound, ""))
	}
	bundle, err := r.defaultRecipeBundle()
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	value, err := recipe.NormalizeProjectBundle(project, bundle)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return projectRecipeDraftModel(value), nil
}

// ProjectDataframeRecipeRevisions is the resolver for the projectDataframeRecipeRevisions field.
func (r *queryResolver) ProjectDataframeRecipeRevisions(ctx context.Context, project string) ([]*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return []*model.DataframeRecipeRevision{}, nil
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: project}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	var values []recipe.RecipeRevision
	var err error
	if store, ok := r.recipeRevisions.(recipe.ProjectRevisionStore); ok {
		values, err = store.ListProjectRevisions(ctx, project)
	} else {
		values, err = r.recipeRevisions.List(ctx, project, recipe.ProjectRecipeName(project))
	}
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result := make([]*model.DataframeRecipeRevision, 0, len(values))
	for _, value := range values {
		result = append(result, recipeRevisionModel(value))
	}
	return result, nil
}

// ProjectDataframeRecipeRevision is the resolver for the projectDataframeRecipeRevision field.
func (r *queryResolver) ProjectDataframeRecipeRevision(ctx context.Context, project string, id string) (*model.DataframeRecipeRevision, error) {
	if r.recipeRevisions == nil {
		return nil, nil
	}
	if _, err := r.authorizeRecipeRead(ctx, recipe.RuntimeBindings{Project: project}); err != nil {
		return nil, recipeGraphQLError(err)
	}
	store, ok := r.recipeRevisions.(recipe.ProjectRevisionStore)
	if !ok {
		return nil, recipeGraphQLError(dataframeerrors.NewError(dataframeerrors.CodeBackendUnavailable, "", dataframeerrors.WithRetryable(true)))
	}
	revision, err := store.GetProjectRevision(ctx, project, id)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return recipeRevisionModel(revision), nil
}

// ExplainDataframeRecipe is the resolver for the explainDataframeRecipe field.
func (r *queryResolver) ExplainDataframeRecipe(ctx context.Context, input model.ExplainDataframeRecipeInput) (*model.DataframeRecipeExplanation, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	explanation, err := r.recipeControl.Explain(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result := planExplanation(explanation, input.Name)
	physical, err := r.recipeControl.ExplainPhysical(ctx, input.Name, bindings, input.Live != nil && *input.Live)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	result.Physical = physicalExplanation(physical)
	return result, nil
}

// PreflightDataframeRecipe is the resolver for the preflightDataframeRecipe field.
func (r *queryResolver) PreflightDataframeRecipe(ctx context.Context, input model.PreflightDataframeRecipeInput) (*model.DataframeRecipePreflight, error) {
	bindings, err := graphqlRecipeBindings(input.Bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	bindings, err = r.authorizeRecipeRead(ctx, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	if err := requireRecipeControl(r.recipeControl); err != nil {
		return nil, recipeGraphQLError(err)
	}
	plan, err := r.recipeControl.Resolve(ctx, input.Name, bindings)
	if err != nil {
		return nil, recipeGraphQLError(err)
	}
	return preflightResult(plan, input.Name), nil
}

// FhirGraph is the resolver for the fhirGraph field.
func (r *queryResolver) FhirGraph(ctx context.Context, input model.FhirGraphQueryInput) (*model.FhirGraphQueryResult, error) {
	return r.resolveFHIRGraph(ctx, input)
}

// ExplainFhirGraph is the resolver for the explainFhirGraph field.
func (r *queryResolver) ExplainFhirGraph(ctx context.Context, input model.FhirGraphQueryInput, live *bool) (*model.FhirGraphQueryExplanation, error) {
	return r.resolveExplainFHIRGraph(ctx, input, live)
}

// Mutation returns executor.MutationResolver implementation.
func (r *Resolver) Mutation() executor.MutationResolver { return &mutationResolver{r} }

// Query returns executor.QueryResolver implementation.
func (r *Resolver) Query() executor.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
