package clickhouse

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/calypr/loom/graphqlapi/model"
)

// DataframeDatasets is the resolver for the dataframeDatasets field.
func (r *queryResolver) DataframeDatasets(ctx context.Context) ([]*model.DataframeMaterialization, error) {
	panic(fmt.Errorf("not implemented: DataframeDatasets - dataframeDatasets"))
}

// DataframeDataset is the resolver for the dataframeDataset field.
func (r *queryResolver) DataframeDataset(ctx context.Context, input model.DataframeDatasetInput) (*model.DataframeMaterialization, error) {
	panic(fmt.Errorf("not implemented: DataframeDataset - dataframeDataset"))
}

// DataframeRows is the resolver for the dataframeRows field.
func (r *queryResolver) DataframeRows(ctx context.Context, input model.DataframeRowsInput) (*model.DataframeRowConnection, error) {
	panic(fmt.Errorf("not implemented: DataframeRows - dataframeRows"))
}

// DataframeAggregate is the resolver for the dataframeAggregate field.
func (r *queryResolver) DataframeAggregate(ctx context.Context, input model.DataframeAggregateInput) (*model.DataframeAggregateResult, error) {
	panic(fmt.Errorf("not implemented: DataframeAggregate - dataframeAggregate"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
