package clickhouse

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"

	materializationapi "github.com/calypr/loom/graphqlapi/materialization"
	"github.com/calypr/loom/graphqlapi/model"
)

// DataframeDatasets is the resolver for the dataframeDatasets field.
func (r *queryResolver) DataframeDatasets(ctx context.Context) ([]*model.DataframeMaterialization, error) {
	values, err := r.service.Datasets(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.DataframeMaterialization, 0, len(values))
	for _, value := range values {
		result = append(result, materializationapi.Model(value))
	}
	return result, nil
}

// DataframeDataset is the resolver for the dataframeDataset field.
func (r *queryResolver) DataframeDataset(ctx context.Context, input model.DataframeDatasetInput) (*model.DataframeMaterialization, error) {
	value, err := r.service.Dataset(ctx, input)
	if err != nil {
		return nil, err
	}
	return materializationapi.Model(*value), nil
}

// DataframeRows is the resolver for the dataframeRows field.
func (r *queryResolver) DataframeRows(ctx context.Context, input model.DataframeRowsInput) (*model.DataframeRowConnection, error) {
	page, err := r.service.Rows(ctx, input)
	if err != nil {
		return nil, err
	}
	rows, err := json.Marshal(page.Rows)
	if err != nil {
		return nil, err
	}
	var cursor *string
	if page.NextCursor != "" {
		cursor = &page.NextCursor
	}
	total := int(page.TotalCount)
	return &model.DataframeRowConnection{
		Materialization: materializationapi.Model(page.Materialization),
		Columns:         page.Columns,
		Rows:            rows,
		TotalCount:      &total,
		PageInfo:        &model.DataframePageInfo{HasNextPage: page.HasNext, EndCursor: cursor},
	}, nil
}

// DataframeAggregate is the resolver for the dataframeAggregate field.
func (r *queryResolver) DataframeAggregate(ctx context.Context, input model.DataframeAggregateInput) (*model.DataframeAggregateResult, error) {
	result, err := r.service.AggregateInput(ctx, input)
	if err != nil {
		return nil, err
	}
	return &model.DataframeAggregateResult{
		Materialization: materializationapi.Model(result.Materialization),
		Columns:         result.Columns,
		Rows:            materializationapi.AggregateRows(result.Rows),
	}, nil
}

// DataframeAggregations is the resolver for the dataframeAggregations field.
func (r *queryResolver) DataframeAggregations(ctx context.Context, input model.DataframeAggregationsInput) (*model.DataframeAggregationsResult, error) {
	result, err := r.service.AggregationsInput(ctx, input)
	if err != nil {
		return nil, err
	}
	aggregations, err := materializationapi.AggregationsJSON(result)
	if err != nil {
		return nil, err
	}
	return &model.DataframeAggregationsResult{Materialization: materializationapi.FederatedMaterialization(result.Dataset), Aggregations: aggregations}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
