export const registry = Object.freeze([
  Object.freeze({
    id: 'builder-controls',
    workflow: 'supported-builder-controls',
    hooks: ['useCreateExplorerAuthoringMutation', 'useApplyExplorerBuilderCommandsV2Mutation', 'useReconcileExplorerBuilderV2Mutation', 'usePreviewExplorerAuthoringV2Mutation', 'useGetExplorerAuthoringCapabilityV2Query', 'useDeleteExplorerAuthoringMutation', 'useKeyedQuery'],
    endpoints: ['POST /api/v1/projects/{project}/explorers', 'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/commands', 'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/reconcile'],
    requiredTransitions: ['duplicate, rename, select, delete table and reload', 'copy Explorer and retain fixture rows', 'Recompile calls the backend and restores preview', 'create a verified-ID Patient table and wait for its current-draft preview before Add columns is enabled'],
    gateReasons: ['Delete table needs a selected table', 'Recompile must obtain a new backend receipt after a failed automatic compile', 'the first-table readiness case observes only the verified-ID Patient flow'],
    script: 'builder-controls.mjs',
    cases: ['tables', 'recompile', 'first-table'],
    requiredChecks: {
      tables: ['duplicated and renamed tables survive reload', 'newly duplicated table is selected immediately', 'newly duplicated table selection survives reload', 'manual table selection survives reload', 'deleted table stays absent after reload', 'selected-table deletion immediately falls back to the remaining table', 'selected-table removal falls back to the remaining table after reload', 'copied Explorer retains configured fields after reload', 'deleting the last table persists an empty workspace'],
      recompile: ['Recompile invokes the backend compiler completed', 'Recompile returned a successful compilation response', 'Preview renders both independent fixture Patients'],
      'first-table': [
        'Add columns stays disabled until a current-draft preview is accepted',
        'Add columns becomes enabled after the accepted current-draft preview',
        'first Patient table uses its verified ID field',
        'Preview renders both independent fixture Patients',
        'Add columns opens from the verified-ID first table',
        'Add columns closes from the verified-ID first table',
      ],
    },
    coverage: [
      { feature: 'table duplicate/rename/delete and Explorer copy', status: 'implemented' },
      { feature: 'selected table restore and deletion fallback', status: 'implemented', reason: 'The registered tables case verifies immediate auto-selection and reload restoration after duplication, manual selection restoration, and fallback persistence after deleting the selected table.' },
      { feature: 'Recompile after failed compilation', status: 'implemented', reason: 'The registered recovery case passes after the automatic-preview ownership fix; save/reload remains outside this case.' },
      { feature: 'Explorer deletion and capability controls', status: 'untested', reason: 'The Builder capability query feeds this feature gate, but registered cases exercise table controls and do not test the capability response or Explorer deletion path.' },
    ],
  }),
  Object.freeze({
    id: 'builder-load',
    workflow: 'builder-load-errors',
    hooks: [
      'useGetExplorerAuthoringExplorersQuery',
      'useGetExplorerBuilderStateV2Query',
    ],
    endpoints: [
      'GET /api/v1/projects/{project}/explorers',
      'GET /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/builder',
    ],
    requiredTransitions: [
      'builder shell loads the selected owned Explorer',
      'list and builder-state read faults show the V2 error alert and an actionable in-app retry',
      'reload separately restores list or builder-state reads when Retry is unavailable',
    ],
    gateReasons: [
      'builder load error currently has no retry control',
    ],
    script: 'builder-load.mjs',
    cases: ['list', 'state'],
    requiredChecks: {
      list: ['builder failure is exposed in an alert', 'builder failure exposes an actionable in-app retry', 'builder recovered through in-app Retry'],
      state: ['builder failure is exposed in an alert', 'builder failure exposes an actionable in-app retry', 'builder recovered through in-app Retry'],
    },
    coverage: [
      { feature: 'builder initial load', status: 'implemented' },
      { feature: 'builder list failure display', status: 'implemented' },
      { feature: 'builder state failure display', status: 'implemented' },
      { feature: 'builder reload recovery', status: 'implemented' },
      { feature: 'builder in-app retry', status: 'implemented' },
    ],
  }),
  Object.freeze({
    id: 'builder-authoring',
    workflow: 'builder-authoring-preview-persistence',
    hooks: [
      'useGetExplorerAuthoringExplorersQuery',
      'useGetExplorerBuilderStateV2Query',
      'useCreateExplorerAuthoringMutation',
      'useApplyExplorerBuilderCommandsV2Mutation',
      'useReconcileExplorerBuilderV2Mutation',
      'useGetExplorerCandidateSuggestionsV2Mutation',
      'usePreviewExplorerAuthoringV2Mutation',
      'usePublishExplorerAuthoringV2Mutation',
      'useAssessExplorerRowChangeMutation',
      'useResolveConfiguredColumnContextsQuery',
      'useResolvePopulationSelectionQuery',
      'usePopulationMappingMutation',
    ],
    endpoints: [
      'POST /api/v1/projects/{project}/explorers',
      'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/commands',
      'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/reconcile',
      'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/suggestions',
      'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/preview',
      'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/publish',
      'POST /api/v1/projects/{project}/explorers/{explorer}/authoring/v2/construction-choice-proposals',
    ],
    requiredTransitions: [
      'create blank Explorer and first table',
      'select Patient root and wait for suggestions',
      'add patient id and gender filter through actionable controls',
      'automatic Preview returns real fixture rows after Apply columns within 5 seconds',
      'Observation.component source EXPANDED distinguishes literal empty arrays from a missing property under PRESERVE_PARENT and EXCLUDE',
      'canceling an EXCLUDE row-definition edit preserves the saved PRESERVE_PARENT source shape before applying EXCLUDE',
      'Publish and reload preserve the selected table and configured columns',
      'bind exactly the two fixture Patient refs into one named cohort',
      'recode distinct Patient.id values to one category and verify ALL→ONE→ALL',
      'remove recoding and reload the exact raw ALL cohort binding',
      'author EXPAND directly from the named cohort Patient.id ALL list and verify exact IDs before and after Apply, edit, removal, and reload',
    ],
    gateReasons: [
      'all clicks require visible enabled controls and center-point hit testing',
      'Patient candidates are loaded from the Builder catalog and rendered as controls',
      'suggestion transport failure and retry remain untested because the dev catalog already supplies candidates',
      'Apply columns must render its automatic preview and retain both fixture Patient identities',
      'the repeated-empty case requires an isolated LOOM_DEV_FIXTURE_DIR with exact component alpha/beta items, a literal empty array, and a missing component property',
      'cohort-expand creates only fixture selection/group state through setup requests; all Builder edits and lifecycle operations use native controls',
    ],
    script: 'builder-authoring.mjs',
    cases: ['suggestions', 'authoring', 'cohort-recode', 'cohort-expand', 'repeated-empty'],
    requiredChecks: {
      suggestions: ['catalog-backed Patient candidates are rendered', 'Patient ID candidate control is visible and actionable'],
      authoring: ['Preview renders both independent fixture Patients', 'publish endpoint returned success', 'published Builder table and configured fields survive reload'],
      'repeated-empty': [
        'case started with a fresh owned project and the exact repeated-empty fixture contract',
        'native source-row lifecycle remains in the exact isolated project, generation, and Explorer',
        'Observation root Preview contains the three exact fixture IDs before source expansion',
        'source Preview starts with one direct Observation identity column',
        'source EXPANDED chooser exposes the exact Observation.component[] collection',
        'source-row preview defaults to PRESERVE_PARENT and predicts four rows from three source records',
        'Cancel leaves all three original source Observation IDs unchanged',
        'PRESERVE_PARENT keeps the literal-empty and missing parent while expanding both component items',
        'source EXPANDED rows expose the scalar component code text field for exact item verification',
        'native component code field offers a selectable FIRST scalar form',
        'native item-field proposal renders exact alpha, beta, explicit-empty, and missing pairs',
        'saved PRESERVE_PARENT source rows show exact Observation/component item multiplicity',
        'PRESERVE_PARENT source EXPANDED rows and item values survive Builder reload',
        'reload keeps the same authorized fixture project, generation, and Explorer',
        'reloaded Rows controls restore component[] and PRESERVE_PARENT with no authored construction step',
        'EXCLUDE is available in the saved EXPANDED row definition',
        'EXCLUDE row-definition comparison shows four base rows and 2 candidate rows',
        'Cancel retains saved PRESERVE_PARENT pairs and all four rows',
        'Cancel retains the same source row choice and PRESERVE_PARENT policy',
        'Cancel keeps the exact same expanded source row choice',
        'EXCLUDE source rows retain the two exact populated component items',
        'EXCLUDE source EXPANDED rows and component items survive Builder reload',
        'EXCLUDE reload keeps the same authorized fixture project, generation, and Explorer',
        'reloaded Rows controls restore component[] and EXCLUDE without authored history',
        'Rows settings offers the original one-row-per-source-record shape for removal',
        'removing source EXPANDED previews a two-to-three row comparison',
        'source RECORDS restoration retains exact Observation/component first-value pairs after Apply',
        'source Observation/component first-value pairs survive Builder reload after row restoration',
        'final reload keeps the exact fixture project, generation, and Explorer',
        'removal persists the source RECORDS row definition without an authored EXPAND step',
        'choose Observation root and render the three source rows action-to-render within budget',
        'open row-shape settings for source expansion action-to-render within budget',
        'open the native repeated-source expansion dialog action-to-render within budget',
        'preview PRESERVE_PARENT for Observation.component[] without applying it action-to-render within budget',
        'Cancel the source expansion proposal action-to-render within budget',
        'return to the table after cancelling source expansion action-to-render within budget',
        'reopen the native repeated-source expansion dialog action-to-render within budget',
        'preview the source expansion that will be applied action-to-render within budget',
        'Apply source EXPANDED row definition with PRESERVE_PARENT action-to-render within budget',
        'return to the table after applying source expansion action-to-render within budget',
        'open native source and form choices for the component code text field action-to-render within budget',
        'preview component code text with the native FIRST form action-to-render within budget',
        'apply component code text field to the expanded source rows action-to-render within budget',
        'open source EXPANDED row settings after reload action-to-render within budget',
        'preview EXCLUDE through the native saved-row policy control before Cancel action-to-render within budget',
        'Cancel the EXCLUDE row-definition edit action-to-render within budget',
        'reopen the source EXPANDED row definition after Cancel action-to-render within budget',
        'preview EXCLUDE again from the same saved source-row definition action-to-render within budget',
        'apply EXCLUDE to the saved source EXPANDED row definition action-to-render within budget',
        'open EXCLUDE source row definition after reload action-to-render within budget',
        'preview removing source expansion by restoring one row per source record action-to-render within budget',
        'apply source-row removal and restore all three fixture Observation IDs action-to-render within budget',
        'verify the restored source row definition after reload action-to-render within budget',
      ],
      'cohort-recode': [
        'fixture cohort binds exactly the two independent Patient IDs',
        'Patient.id starts as distinct raw values under ALL',
        'different literal Patient IDs recode to one shared category under ALL',
        'ONE accepts different raw Patient IDs after they recode to the same category',
        'transformed ONE policy and exact recoding survive reload',
        'returning from ONE to ALL restores the shared-category array',
        'removing recoding restores both exact raw Patient IDs under ALL',
        'raw ALL restoration survives reload on the same cohort and column identity',
      ],
      'cohort-expand': [
        'two fixture Patient rows are read from the independent fixture oracle',
        'fixture named cohort revision contains exactly the two Patients',
        'native Configure rows exposes and selects the exact saved cohort',
        'native Configure rows applies the exact cohort and retains its displayed name',
        'Patient.id is added natively with ALL and its exact two-value array',
        'native Configure rows exposes an actionable Make one row per list value control',
        'automatic authored EXPAND proposal renders both exact IDs and repeats the named cohort label',
        'native EXPAND proposal exposes an actionable Cancel control',
        'Cancel leaves cohort shape, membership, and ALL array unchanged',
        'native EXPAND proposal exposes an actionable Apply control after exact preview',
        'Apply saves EXPAND from the exact member ID list with retained cohort rows',
        'saved EXPAND, exact IDs, and named cohort label survive reload',
        'editing saved EXPAND preserves its input and output identities and exact values',
        'edited EXPAND label and exact rows survive reload',
        'native Rows history exposes an actionable saved EXPAND removal',
        'EXPAND removal proposal previews the restored cohort and exact ALL ID array',
        'removing EXPAND restores the original one-row named cohort with its exact ALL array',
        'final reload restores the exact cohort source and raw ALL member values',
      ],
    },
    coverage: [
      { feature: 'create blank Explorer and first table', status: 'implemented' },
      { feature: 'Patient graph root selection', status: 'implemented' },
      { feature: 'catalog-backed Patient candidate controls', status: 'implemented' },
      { feature: 'suggestion transport failure and retry', status: 'untested', reason: 'The isolated development Builder catalog already contains Patient candidates, so ensureSuggestions returns without issuing the lazy suggestions request.' },
      { feature: 'column projection and filter authoring', status: 'implemented' },
      { feature: 'automatic Preview and action-to-render timing', status: 'implemented' },
      { feature: 'Publish and reload persistence', status: 'implemented' },
      { feature: 'Explorer selection', status: 'untested' },
      { feature: 'table reorder', status: 'untested' },
      { feature: 'existing table row-root change assessment', status: 'untested', reason: 'The registered authoring case selects the root when creating its first table; it does not assess replacing the root on an existing table.' },
      { feature: 'configured-column interpretation context', status: 'untested', reason: 'Basic authoring adds columns and publishes, but it does not inspect or assert the saved-column context.' },
      { feature: 'graph route editing', status: 'untested' },
      { feature: 'starting-record selection', status: 'untested', reason: 'No registered authoring case attaches or resolves a saved starting selection.' },
      { feature: 'named cohort selection', status: 'implemented', reason: 'Registered cohort-recode basic lifecycle passes with two independently known Patient refs; real CDA membership variants have separate cases.' },
      { feature: 'transformed named-cohort member values and ALL/ONE policy', status: 'implemented', reason: 'Registered cohort-recode passes exact ALL/ONE recode, reload and removal/restoration on the basic fixture; CDA follow-up remains separate.' },
      { feature: 'authored list EXPAND from a named-cohort ALL member field', status: 'untested', reason: 'The registered native lifecycle case is staged; root must run it against an owned fresh fixture before marking this transition verified.' },
      { feature: 'raw ONE disagreement rejection for two Patient IDs', status: 'untested', reason: 'The basic transformed cycle restores raw ALL and stops before attempting the expected raw ONE rejection; the CDA transformed-category driver covers that refusal.' },
      { feature: 'selected-resource population coverage check', status: 'untested', reason: 'No registered case attaches a saved selection and published receipt, then activates the coverage check.' },
      { feature: 'grouping rows', status: 'untested' },
      { feature: 'related-record rows', status: 'untested' },
      { feature: 'repeated-value rows', status: 'untested', reason: 'The registered repeated-empty case covers only Observation.component literal-empty and missing policies; other repeated fields and source shapes remain untested.' },
      { feature: 'Observation.component literal-empty and missing-list policies with saved Expand lifecycle', status: 'implemented', reason: 'The registered case checks exact ID/item pairs for PRESERVE_PARENT and EXCLUDE, Cancel retention of the saved policy/step identity, reloads both policies, and removes Expand.' },
      { feature: 'ordinary Pivot', status: 'untested' },
      { feature: 'coded Pivot', status: 'untested' },
      { feature: 'Unpivot', status: 'untested' },
      { feature: 'Filter rows', status: 'untested' },
      { feature: 'direct columns', status: 'untested' },
      { feature: 'coded columns', status: 'untested' },
      { feature: 'related columns', status: 'untested' },
      { feature: 'ONE/ALL contributing values', status: 'untested' },
      { feature: 'contributor rules', status: 'untested' },
      { feature: 'missing-match policies', status: 'untested' },
      { feature: 'coverage inspection', status: 'untested' },
      { feature: 'column renaming', status: 'untested' },
      { feature: 'column chart configuration', status: 'untested' },
      { feature: 'column removal', status: 'untested' },
      { feature: 'preview limits', status: 'untested' },
      { feature: 'preview contract panels', status: 'untested' },
    ],
  }),
  Object.freeze({
    id: 'viewer-query',
    workflow: 'viewer-query-fault-retry',
    hooks: ['useLoomRuntime', 'useLoomOutput', 'useCellTraceMutation'],
    endpoints: [
      'GET /api/v1/projects/{project}/explorers/{explorer}',
      'POST /graphql/graph',
      'LoomClient.exportOutput',
    ],
    requiredTransitions: [
      'publish a fixture Explorer through Builder UI',
      'Viewer runtime loads and renders fixture rows',
      'one query read fault shows an actionable Retry control',
      'Retry loads real rows and filter facets',
    ],
    gateReasons: [
      'viewer Retry is accepted only after hit testing the real control',
      'fault injection targets one POST /graphql/graph read and is restored in finally',
      'custom URLs verify query recovery without assuming development fixture row or facet contents',
      'filter selection persistence across a full reload is not claimed',
    ],
    script: 'viewer-query.mjs',
    cases: ['output'],
    requiredChecks: {
      output: {
        owned: ['injected result-query error is visibly reported', 'result-query error exposes an actionable Retry control', 'retry result query completed', 'retried Viewer results contain both independent fixture Patients'],
        custom: ['injected result-query error is visibly reported', 'result-query error exposes an actionable Retry control', 'retry result query completed', 'Retry restored the custom output table'],
      },
    },
    coverage: [
      { feature: 'Viewer runtime load', status: 'implemented' },
      { feature: 'output query failure display and Retry', status: 'implemented' },
      { feature: 'facet checkbox and filtered query', status: 'untested', reason: 'The published development fixture declares no runtime filters; this case cannot open a facet.' },
      { feature: 'filter selection persistence across reload', status: 'untested' },
      { feature: 'shared filters', status: 'untested' },
      { feature: 'sorting', status: 'untested' },
      { feature: 'pagination', status: 'untested' },
      { feature: 'charts', status: 'untested' },
      { feature: 'row details', status: 'untested' },
      { feature: 'receipt-bound cell explanation/source trace', status: 'untested', reason: 'The Viewer query case verifies result-query recovery; it does not activate the feature-cell Explain action.' },
      { feature: 'custom actions', status: 'untested' },
      { feature: 'CSV export', status: 'untested' },
    ],
  }),
]);

export const getScenario = (id) => {
  const scenario = registry.find((entry) => entry.id === id);
  if (!scenario) throw new Error('unknown scenario: ' + id);
  return scenario;
};

export const requiredChecksFor = (scenario, caseName, custom = false) => {
  const checks = scenario.requiredChecks?.[caseName];
  const selected = Array.isArray(checks) ? checks : checks?.[custom ? 'custom' : 'owned'];
  if (!Array.isArray(selected) || !selected.length) throw new Error(`missing required checks for ${scenario.id}/${caseName}`);
  return selected;
};

export const coverageDrift = (entries = registry) => entries.flatMap((entry) => [
  ...entry.coverage.filter((coverage) => !['implemented', 'untested', 'failed'].includes(coverage.status))
    .map((coverage) => entry.id + ': invalid coverage status ' + coverage.status),
  ...entry.cases.flatMap((caseName) => {
    try { requiredChecksFor(entry, caseName); return []; }
    catch (error) { return [error.message]; }
  }),
]);
