package main

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func generateExtract(schema *Schema, path string) error {
	var sb strings.Builder
	var keys []string
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	sb.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	sb.WriteString("package fhir\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"bytes\"\n")
	sb.WriteString("\t\"crypto/sha1\"\n")
	sb.WriteString("\t\"encoding/hex\"\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"hash\"\n")
	sb.WriteString("\t\"reflect\"\n")
	sb.WriteString("\t\"strconv\"\n")
	sb.WriteString("\t\"strings\"\n")
	sb.WriteString("\t\"sync\"\n")
	sb.WriteString("\t\"github.com/google/uuid\"\n")
	sb.WriteString("\t\"github.com/bytedance/sonic\"\n")
	sb.WriteString("\tfhirschema \"github.com/calypr/loom/internal/fhir/schema\"\n")
	sb.WriteString(")\n\n")

	// 1. Write EdgeDocument struct definition
	sb.WriteString(`// EdgeDocument represents an edge in ArangoDB.
type EdgeDocument struct {
	Key      string ` + "`" + `json:"_key"` + "`" + `
	From     string ` + "`" + `json:"_from"` + "`" + `
	To       string ` + "`" + `json:"_to"` + "`" + `
	Label    string ` + "`" + `json:"label"` + "`" + `
	Project  string ` + "`" + `json:"project"` + "`" + `
	FromType string ` + "`" + `json:"from_type"` + "`" + `
	ToType   string ` + "`" + `json:"to_type"` + "`" + `
	SourcePath string ` + "`" + `json:"source_path,omitempty"` + "`" + `
	ExtensionURL string ` + "`" + `json:"extension_url,omitempty"` + "`" + `
}

type nestedLinkRule struct {
	SourceType string
	Path []string
	Label string
	TargetPatterns []string
	Backrefs []string
}

var nestedLinkRules = []nestedLinkRule{
`)
	for _, typeName := range keys {
		definition := schema.Defs[typeName]
		if isFHIRRootResourceDefinition(typeName, definition) {
			continue
		}
		for _, link := range definition.Links {
			path := pointerPathParts(link.TemplatePointers.ID)
			if len(path) == 0 || strings.TrimSpace(link.Rel) == "" {
				continue
			}
			patterns := nestedLinkTargetPatterns(schema, link)
			if len(patterns) == 0 {
				continue
			}
			sb.WriteString("\t{SourceType: " + strconv.Quote(typeName) + ", Path: []string{")
			for _, part := range path {
				sb.WriteString(strconv.Quote(part) + ",")
			}
			sb.WriteString("}, Label: " + strconv.Quote(link.Rel) + ", TargetPatterns: []string{")
			for _, pattern := range patterns {
				sb.WriteString(strconv.Quote(pattern) + ",")
			}
			sb.WriteString("}, Backrefs: []string{")
			for _, backref := range link.TargetHints.Backref {
				if strings.TrimSpace(backref) != "" {
					sb.WriteString(strconv.Quote(backref) + ",")
				}
			}
			sb.WriteString("}},\n")
		}
	}
	sb.WriteString(`}

var nestedLinkCoverage = map[string]struct{}{
`)
	for _, key := range nestedLinkCoverageKeys(schema) {
		sb.WriteString("\t" + strconv.Quote(key) + ": {},\n")
	}
	sb.WriteString(`}

// Result of validation and edge extraction.
type Result struct {
	ObjectID     string
	ResourceType string
	Vertex       any
	Edges        []json.RawMessage
}

// Global namespace UUID constant computed from "calypr-public.ohsu.edu"
var namespaceUUID = uuid.NewMD5(uuid.NameSpaceDNS, []byte("calypr-public.ohsu.edu"))

var sha1Pool = sync.Pool{
	New: func() any {
		return sha1.New()
	},
}

var bufferPool = sync.Pool{
	New: func() any {
		return &bytes.Buffer{}
	},
}

func fastUUIDSHA1(space uuid.UUID, data []byte) string {
	h := sha1Pool.Get().(hash.Hash)
	h.Reset()
	h.Write(space[:])
	h.Write(data)
	var hashBytes [20]byte
	h.Sum(hashBytes[:0])
	sha1Pool.Put(h)

	// format uuid v5: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	// version 5 (SHA-1)
	hashBytes[6] = (hashBytes[6] & 0x0f) | 0x50
	hashBytes[8] = (hashBytes[8] & 0x3f) | 0x80

	var buf [36]byte
	hex.Encode(buf[0:8], hashBytes[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], hashBytes[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], hashBytes[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], hashBytes[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], hashBytes[10:16])

	return string(buf[:])
}

func getEdgeUUID(a, b, c string) string {
	buf := bufferPool.Get().(*bytes.Buffer)
	buf.Reset()
	buf.WriteString(a)
	buf.WriteByte('-')
	buf.WriteString(b)
	buf.WriteByte('-')
	buf.WriteString(c)
	uuidStr := fastUUIDSHA1(namespaceUUID, buf.Bytes())
	bufferPool.Put(buf)
	return uuidStr
}

func collectionID(resourceType, id string) string {
	return sanitizeKey(resourceType) + "/" + sanitizeKey(id)
}

func sanitizeKey(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "_"
	}
	needsSanitization := false
	for i := 0; i < len(value); i++ {
		r := value[i]
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') ||
			r == '_' || r == '-' || r == ':' || r == '.' || r == '@' || r == '(' || r == ')' ||
			r == '+' || r == ',' || r == '=' || r == ';' || r == '$' || r == '!' || r == '*' ||
			r == '\'' || r == '%' {
			// clean character
		} else {
			needsSanitization = true
			break
		}
	}
	if !needsSanitization {
		return value
	}

	var sb strings.Builder
	sb.Grow(len(value))
	for _, r := range value {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') ||
			r == '_' || r == '-' || r == ':' || r == '.' || r == '@' || r == '(' || r == ')' ||
			r == '+' || r == ',' || r == '=' || r == ';' || r == '$' || r == '!' || r == '*' ||
			r == '\'' || r == '%' {
			sb.WriteRune(r)
		} else {
			sb.WriteRune('_')
		}
	}
	return sb.String()
}

func splitFHIRReference(ref string) (string, string, bool) {
	firstSlash := strings.IndexByte(ref, '/')
	if firstSlash <= 0 || firstSlash == len(ref)-1 {
		return "", "", false
	}
	targetType := ref[:firstSlash]
	targetID := ref[firstSlash+1:]
	if secondSlash := strings.IndexByte(targetID, '/'); secondSlash != -1 {
		targetID = targetID[:secondSlash]
	}
	if targetID == "" {
		return "", "", false
	}
	return targetType, targetID, true
}

func buildEdgeRawJSON(key, from, to, label, projectJSON, fromType, toType string) json.RawMessage {
	var buf bytes.Buffer
	buf.Grow(256)
	buf.WriteString("{\"_key\":\"")
	buf.WriteString(key)
	buf.WriteString("\",\"_from\":\"")
	buf.WriteString(from)
	buf.WriteString("\",\"_to\":\"")
	buf.WriteString(to)
	buf.WriteString("\",\"label\":\"")
	buf.WriteString(label)
	buf.WriteString("\",\"project\":")
	buf.WriteString(projectJSON)
	buf.WriteString(",\"from_type\":\"")
	buf.WriteString(fromType)
	buf.WriteString("\",\"to_type\":\"")
	buf.WriteString(toType)
	buf.WriteString("\"}")
	return json.RawMessage(buf.Bytes())
}

func buildNestedEdgeRawJSON(key, from, to, label, projectJSON, fromType, toType, sourcePath, extensionURL string) json.RawMessage {
	var buf bytes.Buffer
	buf.Grow(320)
	buf.WriteString("{\"_key\":")
	buf.WriteString(strconv.Quote(key))
	buf.WriteString(",\"_from\":")
	buf.WriteString(strconv.Quote(from))
	buf.WriteString(",\"_to\":")
	buf.WriteString(strconv.Quote(to))
	buf.WriteString(",\"label\":")
	buf.WriteString(strconv.Quote(label))
	buf.WriteString(",\"project\":")
	buf.WriteString(projectJSON)
	buf.WriteString(",\"from_type\":")
	buf.WriteString(strconv.Quote(fromType))
	buf.WriteString(",\"to_type\":")
	buf.WriteString(strconv.Quote(toType))
	buf.WriteString(",\"source_path\":")
	buf.WriteString(strconv.Quote(sourcePath))
	if extensionURL != "" {
		buf.WriteString(",\"extension_url\":")
		buf.WriteString(strconv.Quote(extensionURL))
	}
	buf.WriteByte('}')
	return json.RawMessage(buf.Bytes())
}

func nestedEdgeUUID(parts ...string) string {
	buf := bufferPool.Get().(*bytes.Buffer)
	buf.Reset()
	for _, part := range parts {
		buf.WriteString(strconv.Itoa(len(part)))
		buf.WriteByte(':')
		buf.WriteString(part)
	}
	key := fastUUIDSHA1(namespaceUUID, buf.Bytes())
	bufferPool.Put(buf)
	return key
}

func walkNestedFHIRLinks(value reflect.Value, sourcePath, extensionURL, project, sourceType, sourceID string, projectJSON string, seen *map[string]struct{}, edges *[]json.RawMessage) {
	for value.IsValid() && (value.Kind() == reflect.Pointer || value.Kind() == reflect.Interface) {
		if value.IsNil() {
			return
		}
		value = value.Elem()
	}
	if !value.IsValid() {
		return
	}
	if value.Kind() == reflect.Slice || value.Kind() == reflect.Array {
		for index := 0; index < value.Len(); index++ {
			walkNestedFHIRLinks(value.Index(index), sourcePath+"[]", extensionURL, project, sourceType, sourceID, projectJSON, seen, edges)
		}
		return
	}
	if value.Kind() != reflect.Struct {
		return
	}

	valueType := value.Type()
	if valueType.Name() == "Extension" {
		if urlField := value.FieldByName("URL"); urlField.IsValid() && urlField.Kind() == reflect.Pointer && !urlField.IsNil() && urlField.Elem().Kind() == reflect.String {
			extensionURL = urlField.Elem().String()
		}
	}

	for _, rule := range nestedLinkRules {
		if rule.SourceType != valueType.Name() {
			continue
		}
		for _, reference := range nestedReferenceValues(value, rule.Path, sourcePath) {
			refType, targetID, ok := splitFHIRReference(reference.value)
			if !ok {
				continue
			}
			refType, ok = fhirschema.ConcreteResourceType(refType)
			if !ok || !nestedLinkAllowsTarget(rule.TargetPatterns, refType) {
				continue
			}
			if _, alreadyExtracted := nestedLinkCoverage[nestedLinkCoverageKey(sourceType, rule.SourceType, rule.Label, refType)]; alreadyExtracted {
				continue
			}
			label := nestedRelationshipLabel(sourceType, reference.path, rule.Path, rule.Label)
			forwardKey := nestedEdgeUUID(project, sourceType, sourceID, refType, targetID, label, reference.path, extensionURL)
			appendNestedEdge(edges, seen, forwardKey, collectionID(sourceType, sourceID), collectionID(refType, targetID), label, projectJSON, sourceType, refType, reference.path, extensionURL)
			for _, backref := range rule.Backrefs {
				if strings.TrimSpace(backref) == "" {
					continue
				}
				backrefLabel := nestedRelationshipLabel(sourceType, reference.path, rule.Path, backref)
				backrefKey := nestedEdgeUUID(project, refType, targetID, sourceType, sourceID, backrefLabel, reference.path, extensionURL)
				appendNestedEdge(edges, seen, backrefKey, collectionID(refType, targetID), collectionID(sourceType, sourceID), backrefLabel, projectJSON, refType, sourceType, reference.path, extensionURL)
			}
		}
	}

	for index := 0; index < value.NumField(); index++ {
		field := valueType.Field(index)
		if field.PkgPath != "" || field.Name == "Links" {
			continue
		}
		jsonName := strings.Split(field.Tag.Get("json"), ",")[0]
		if jsonName == "" || jsonName == "-" {
			continue
		}
		walkNestedFHIRLinks(value.Field(index), sourcePath+"."+jsonName, extensionURL, project, sourceType, sourceID, projectJSON, seen, edges)
	}
}

func nestedLinkCoverageKey(resourceType, nestedType, label, targetType string) string {
	return resourceType + "|" + nestedType + "|" + label + "|" + targetType
}

func nestedRelationshipLabel(resourceType, referencePath string, linkPath []string, relation string) string {
	relativePath := strings.TrimPrefix(referencePath, resourceType+".")
	relativePath = strings.ReplaceAll(relativePath, "[]", "")
	linkParts := make([]string, 0, len(linkPath))
	for _, part := range linkPath {
		if part != "-" {
			linkParts = append(linkParts, part)
		}
	}
	linkSuffix := strings.Join(linkParts, ".")
	if linkSuffix != "" && relativePath != linkSuffix {
		relativePath = strings.TrimSuffix(relativePath, "."+linkSuffix)
	} else if relativePath == linkSuffix {
		relativePath = ""
	}
	prefix := strings.ReplaceAll(relativePath, ".", "_")
	if prefix == "" {
		return relation
	}
	return prefix + "_" + relation
}

type nestedReferenceValue struct {
	value string
	path string
}

func nestedReferenceValues(value reflect.Value, path []string, sourcePath string) []nestedReferenceValue {
	if len(path) == 0 {
		for value.IsValid() && (value.Kind() == reflect.Pointer || value.Kind() == reflect.Interface) {
			if value.IsNil() {
				return nil
			}
			value = value.Elem()
		}
		if value.IsValid() && value.Kind() == reflect.String && strings.TrimSpace(value.String()) != "" {
			return []nestedReferenceValue{{value: value.String(), path: sourcePath}}
		}
		return nil
	}
	if !value.IsValid() {
		return nil
	}
	if path[0] == "-" {
		for value.IsValid() && (value.Kind() == reflect.Pointer || value.Kind() == reflect.Interface) {
			if value.IsNil() {
				return nil
			}
			value = value.Elem()
		}
		if value.Kind() != reflect.Slice && value.Kind() != reflect.Array {
			return nil
		}
		var matches []nestedReferenceValue
		for index := 0; index < value.Len(); index++ {
			matches = append(matches, nestedReferenceValues(value.Index(index), path[1:], sourcePath+"[]")...)
		}
		return matches
	}
	for value.IsValid() && (value.Kind() == reflect.Pointer || value.Kind() == reflect.Interface) {
		if value.IsNil() {
			return nil
		}
		value = value.Elem()
	}
	if value.Kind() != reflect.Struct {
		return nil
	}
	for index := 0; index < value.NumField(); index++ {
		field := value.Type().Field(index)
		jsonName := strings.Split(field.Tag.Get("json"), ",")[0]
		if jsonName == path[0] {
			return nestedReferenceValues(value.Field(index), path[1:], sourcePath+"."+jsonName)
		}
	}
	return nil
}

func nestedLinkAllowsTarget(patterns []string, targetType string) bool {
	for _, pattern := range patterns {
		if pattern == "Resource/*" || strings.TrimSuffix(pattern, "/*") == targetType {
			return true
		}
	}
	return false
}

func appendNestedEdge(edges *[]json.RawMessage, seen *map[string]struct{}, key, from, to, label, projectJSON, fromType, toType, sourcePath, extensionURL string) {
	if *seen == nil {
		*seen = make(map[string]struct{}, 8)
	}
	if _, exists := (*seen)[key]; exists {
		return
	}
	(*seen)[key] = struct{}{}
	*edges = append(*edges, buildNestedEdgeRawJSON(key, from, to, label, projectJSON, fromType, toType, sourcePath, extensionURL))
}

`)

	// Keep track of which resource types are supported (those having links metadata in the schema)
	supportedResources := []string{}

	for _, k := range keys {
		def := schema.Defs[k]

		// Only concrete FHIR roots get graph loaders. Backbone definitions and
		// abstract Resource remain available to field/selector generation but
		// never become graph collections or row grains.
		if !isFHIRRootResourceDefinition(k, def) {
			continue
		}

		supportedResources = append(supportedResources, k)

		sb.WriteString(fmt.Sprintf("// ExtractEdges extracts graph links from %s.\n", k))
		sb.WriteString(fmt.Sprintf("func (x *%s) ExtractEdges(project string) ([]json.RawMessage, error) {\n", k))
		sb.WriteString("\tvar edges []json.RawMessage\n")
		sb.WriteString("\tif x == nil || x.ID == nil {\n\t\treturn edges, nil\n\t}\n")
		sb.WriteString("\tid := *x.ID\n")
		sb.WriteString("\tsourceType := \"" + k + "\"\n")
		sb.WriteString("\tprojectJSON := strconv.Quote(project)\n")
		sb.WriteString("\t_ = id\n")
		sb.WriteString("\t_ = sourceType\n")
		sb.WriteString("\t_ = projectJSON\n")
		sb.WriteString("\tvar seen map[string]struct{}\n")
		sb.WriteString("\t_ = seen\n")

		// Generate link extraction code statically!
		for _, link := range def.Links {
			ptr := link.TemplatePointers.ID
			if ptr == "" {
				continue
			}

			// We need to generate code to traverse to templatePointers
			pathParts := strings.Split(ptr, "/")[1:]
			traversalCode, err := generateTraversalCode(schema, k, pathParts, "x", k, link, "\t")
			if err != nil {
				return err
			}
			sb.WriteString(traversalCode)
		}
		sb.WriteString(fmt.Sprintf("\twalkNestedFHIRLinks(reflect.ValueOf(x), %q, \"\", project, sourceType, id, projectJSON, &seen, &edges)\n", k))

		sb.WriteString("\treturn edges, nil\n")
		sb.WriteString("}\n\n")
	}

	// 2. Write the unified ValidateAndExtract entrypoint
	sb.WriteString("// ValidateAndExtract parses, validates, and extracts edges for a FHIR resource.\n")
	sb.WriteString("func ValidateAndExtract(raw []byte, resourceType string, project string) (Result, error) {\n")
	sb.WriteString("\tswitch resourceType {\n")
	for _, res := range supportedResources {
		sb.WriteString(fmt.Sprintf("\tcase %q:\n", res))
		sb.WriteString(fmt.Sprintf("\t\tvar val %s\n", res))
		sb.WriteString("\t\tif err := sonic.Unmarshal(raw, &val); err != nil {\n")
		sb.WriteString("\t\t\treturn Result{}, fmt.Errorf(\"decode error: %w\", err)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tif err := val.Validate(); err != nil {\n")
		sb.WriteString("\t\t\treturn Result{}, fmt.Errorf(\"validation error: %w\", err)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tedges, err := val.ExtractEdges(project)\n")
		sb.WriteString("\t\tif err != nil {\n")
		sb.WriteString("\t\t\treturn Result{}, fmt.Errorf(\"extraction error: %w\", err)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tvar objectID string\n")
		sb.WriteString("\t\tif val.ID != nil {\n\t\t\tobjectID = *val.ID\n\t\t}\n")
		sb.WriteString("\t\treturn Result{\n")
		sb.WriteString("\t\t\tObjectID:     objectID,\n")
		sb.WriteString("\t\t\tResourceType: resourceType,\n")
		sb.WriteString("\t\t\tVertex:       json.RawMessage(raw),\n")
		sb.WriteString("\t\t\tEdges:        edges,\n")
		sb.WriteString("\t\t}, nil\n")
	}
	sb.WriteString("\tdefault:\n")
	sb.WriteString("\t\treturn Result{}, fmt.Errorf(\"unsupported resource type %s\", resourceType)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func pointerPathParts(pointer string) []string {
	if pointer == "" || !strings.HasPrefix(pointer, "/") {
		return nil
	}
	parts := strings.Split(pointer[1:], "/")
	for _, part := range parts {
		if part == "" {
			return nil
		}
	}
	return parts
}

func nestedLinkCoverageKeys(schema *Schema) []string {
	rootTypes := schemaFHIRRootResourceTypes(schema)
	var keys []string
	seen := map[string]struct{}{}
	definitionNames := make([]string, 0, len(schema.Defs))
	for nestedType := range schema.Defs {
		definitionNames = append(definitionNames, nestedType)
	}
	sort.Strings(definitionNames)
	for _, nestedType := range definitionNames {
		nestedDefinition := schema.Defs[nestedType]
		if isFHIRRootResourceDefinition(nestedType, nestedDefinition) {
			continue
		}
		for _, nestedLink := range nestedDefinition.Links {
			if strings.TrimSpace(nestedLink.Rel) == "" {
				continue
			}
			for _, rootType := range rootTypes {
				rootDefinition := schema.Defs[rootType]
				for _, rootLink := range rootDefinition.Links {
					if !schemaPointerComposesLink(schema, rootType, rootLink.TemplatePointers.ID, nestedType, nestedLink.TemplatePointers.ID) {
						continue
					}
					for _, targetType := range rootTypes {
						if !nestedLinkSchemaAllowsTarget(schema, nestedLink, targetType) || !nestedLinkSchemaAllowsTarget(schema, rootLink, targetType) {
							continue
						}
						key := nestedLinkCoverageKey(rootType, nestedType, nestedLink.Rel, targetType)
						if _, exists := seen[key]; exists {
							continue
						}
						seen[key] = struct{}{}
						keys = append(keys, key)
					}
				}
			}
		}
	}
	sort.Strings(keys)
	return keys
}

func nestedLinkCoverageKey(resourceType, nestedType, label, targetType string) string {
	return resourceType + "|" + nestedType + "|" + label + "|" + targetType
}

func nestedLinkSchemaAllowsTarget(schema *Schema, link Link, targetType string) bool {
	for _, pattern := range nestedLinkTargetPatterns(schema, link) {
		if pattern == "Resource/*" || strings.TrimSuffix(pattern, "/*") == targetType {
			return true
		}
	}
	return false
}

func schemaPointerComposesLink(schema *Schema, rootType, pointer, nestedType, nestedPointer string) bool {
	currentType := rootType
	rootParts := pointerPathParts(pointer)
	nestedParts := withoutArrayMarkers(pointerPathParts(nestedPointer))
	for index, part := range rootParts {
		if part == "-" {
			continue
		}
		definition := schema.Defs[currentType]
		if definition == nil {
			return false
		}
		property := definition.Properties[part]
		if property == nil {
			return false
		}
		nextType := property.Ref
		if nextType == "" && property.Items != nil {
			nextType = property.Items.Ref
		}
		nextType = refName(nextType)
		if nextType == nestedType {
			return equalStringSlices(withoutArrayMarkers(rootParts[index+1:]), nestedParts)
		}
		if nextType == "" {
			return false
		}
		currentType = nextType
	}
	return false
}

func withoutArrayMarkers(parts []string) []string {
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		if part != "-" {
			result = append(result, part)
		}
	}
	return result
}

func equalStringSlices(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func nestedLinkTargetPatterns(schema *Schema, link Link) []string {
	var patterns []string
	seen := map[string]struct{}{}
	addPattern := func(pattern string) {
		if _, ok := seen[pattern]; ok {
			return
		}
		seen[pattern] = struct{}{}
		patterns = append(patterns, pattern)
	}
	if target := strings.TrimSpace(refName(link.TargetSchema.Ref)); target != "" && isFHIRRootResourceDefinition(target, schema.Defs[target]) {
		addPattern(target)
	}
	for _, regex := range link.TargetHints.RegexMatch {
		regex = strings.TrimSpace(regex)
		if regex == "" {
			continue
		}
		if regex == "Resource/*" {
			addPattern(regex)
			continue
		}
		candidate := strings.TrimSuffix(regex, "/*")
		if isFHIRRootResourceDefinition(candidate, schema.Defs[candidate]) {
			addPattern(candidate)
		}
	}
	return patterns
}

func generateTraversalCode(schema *Schema, structName string, path []string, varName string, currentType string, link Link, indent string) (string, error) {
	if len(path) == 0 {
		// We have reached the string value (the reference).
		// We emit the edge building code!
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("%srefVal := %s\n", indent, varName))
		sb.WriteString(fmt.Sprintf("%srefType, targetID, ok := splitFHIRReference(refVal)\n", indent))
		sb.WriteString(fmt.Sprintf("%sif ok {\n", indent))
		sb.WriteString(fmt.Sprintf("%s\trefType, ok = fhirschema.ConcreteResourceType(refType)\n", indent))
		sb.WriteString(fmt.Sprintf("%s\tif ok {\n", indent))

		// Match prefix check
		allowAnyMatch := false
		matchPrefix := ""
		for _, rx := range link.TargetHints.RegexMatch {
			if rx == "Resource/*" {
				allowAnyMatch = true
			} else {
				matchPrefix = strings.TrimSuffix(rx, "/*")
			}
		}

		bodyIndent := indent + "\t\t"
		if !allowAnyMatch && matchPrefix != "" {
			sb.WriteString(fmt.Sprintf("%sif refType == %q {\n", bodyIndent, matchPrefix))
			bodyIndent += "\t"
		}

		sb.WriteString(fmt.Sprintf("%sforwardKey := getEdgeUUID(targetID, id, %q)\n", bodyIndent, link.Rel))
		sb.WriteString(fmt.Sprintf("%sif seen == nil {\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\tseen = make(map[string]struct{}, 4)\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%sif _, exists := seen[forwardKey]; !exists {\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\tseen[forwardKey] = struct{}{}\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\tedges = append(edges, buildEdgeRawJSON(\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tforwardKey,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(sourceType, id),\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(refType, targetID),\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\t%q,\n", bodyIndent, link.Rel))
		sb.WriteString(fmt.Sprintf("%s\t\tprojectJSON,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tsourceType,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\trefType,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t))\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))

		// Check if backref exists
		if len(link.TargetHints.Backref) > 0 && link.TargetHints.Backref[0] != "" {
			backref := link.TargetHints.Backref[0]
			sb.WriteString(fmt.Sprintf("%sbackrefKey := getEdgeUUID(id, targetID, %q)\n", bodyIndent, backref))
			sb.WriteString(fmt.Sprintf("%sif seen == nil {\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\tseen = make(map[string]struct{}, 4)\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%sif _, exists := seen[backrefKey]; !exists {\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\tseen[backrefKey] = struct{}{}\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\tedges = append(edges, buildEdgeRawJSON(\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tbackrefKey,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(refType, targetID),\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(sourceType, id),\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\t%q,\n", bodyIndent, backref))
			sb.WriteString(fmt.Sprintf("%s\t\tprojectJSON,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\trefType,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tsourceType,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t))\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
		}

		if !allowAnyMatch && matchPrefix != "" {
			bodyIndent = bodyIndent[:len(bodyIndent)-1]
			sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
		}

		sb.WriteString(fmt.Sprintf("%s\t}\n", indent))
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
		return sb.String(), nil
	}

	part := path[0]

	if part == "-" {
		// VarName must be a slice. Loop over the elements.
		// Wait, what is the item type?
		// We need to look up the parent property to see what its items are.
		// E.g. x.PartOf which is a slice. Let's find what the element type is.
		// We can pass currentType down, but since we are iterating, we need to know the type of items.
		// Let's pass the element type in currentType.
		// If part is "-", then the type of item is currentType.
		loopVar := fmt.Sprintf("item_%d_%s", len(path), strings.ReplaceAll(varName, ".", "_"))
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("%sfor _, %s := range %s {\n", indent, loopVar, varName))
		// Check for nil if item is a pointer
		sb.WriteString(fmt.Sprintf("%s\tif %s != nil {\n", indent+"\t", loopVar))
		subCode, err := generateTraversalCode(schema, structName, path[1:], loopVar, currentType, link, indent+"\t\t")
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
		sb.WriteString(fmt.Sprintf("%s\t}\n", indent))
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
		return sb.String(), nil
	}

	// It's a field name!
	// Look up in schema Defs[currentType] to find property named `part`.
	def, ok := schema.Defs[currentType]
	if !ok {
		return "", fmt.Errorf("definition %s not found in schema while resolving path part %s", currentType, part)
	}

	prop, ok := def.Properties[part]
	if !ok {
		// It could be that part is not a direct property, or it is in some other way.
		// But in graph-fhir.json, they are always properties.
		return "", fmt.Errorf("property %s not found in definition %s", part, currentType)
	}

	fieldName := toGoName(part)
	nextVarName := fmt.Sprintf("%s.%s", varName, fieldName)

	var nextType string
	if prop.Ref != "" {
		nextType = refName(prop.Ref)
	} else if prop.Items != nil && prop.Items.Ref != "" {
		nextType = refName(prop.Items.Ref)
	} else if typeStr, ok := prop.Type.(string); ok && typeStr == "string" {
		nextType = "string"
	}

	var sb strings.Builder
	// If it's a pointer type, check for nil
	goType := getGoType(prop, true) // treat as optional to see if it has pointer prefix
	isPointer := strings.HasPrefix(goType, "*")
	isSlice := strings.HasPrefix(goType, "[]")

	if isPointer {
		sb.WriteString(fmt.Sprintf("%sif %s != nil {\n", indent, nextVarName))
		// If it's a leaf string pointer (like *string), dereference it
		actualVar := nextVarName
		if nextType == "string" {
			actualVar = "*" + nextVarName
		}
		subCode, err := generateTraversalCode(schema, structName, path[1:], actualVar, nextType, link, indent+"\t")
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
	} else if isSlice {
		sb.WriteString(fmt.Sprintf("%sif %s != nil {\n", indent, nextVarName))
		subCode, err := generateTraversalCode(schema, structName, path[1:], nextVarName, nextType, link, indent+"\t")
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
	} else {
		subCode, err := generateTraversalCode(schema, structName, path[1:], nextVarName, nextType, link, indent)
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
	}

	return sb.String(), nil
}
