package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

func generateExtract(schema *Schema, path string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	sb.WriteString("package fhir\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"bytes\"\n")
	sb.WriteString("\t\"crypto/sha1\"\n")
	sb.WriteString("\t\"encoding/hex\"\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"hash\"\n")
	sb.WriteString("\t\"strconv\"\n")
	sb.WriteString("\t\"strings\"\n")
	sb.WriteString("\t\"sync\"\n")
	sb.WriteString("\t\"github.com/google/uuid\"\n")
	sb.WriteString("\t\"github.com/bytedance/sonic\"\n")
	sb.WriteString("\tfhirschema \"github.com/calypr/loom/internal/fhir/schema\"\n")
	sb.WriteString(")\n\n")

	// 1. Write EdgeDocument struct definition
	sb.WriteString(`// EdgeDocument represents an edge in ArangoDB.
type EdgeDocument struct {
	Key      string ` + "`" + `json:"_key"` + "`" + `
	From     string ` + "`" + `json:"_from"` + "`" + `
	To       string ` + "`" + `json:"_to"` + "`" + `
	Label    string ` + "`" + `json:"label"` + "`" + `
	Project  string ` + "`" + `json:"project"` + "`" + `
	FromType string ` + "`" + `json:"from_type"` + "`" + `
	ToType   string ` + "`" + `json:"to_type"` + "`" + `
}

// Result of validation and edge extraction.
type Result struct {
	ObjectID     string
	ResourceType string
	Vertex       any
	Edges        []json.RawMessage
}

// Global namespace UUID constant computed from "calypr-public.ohsu.edu"
var namespaceUUID = uuid.NewMD5(uuid.NameSpaceDNS, []byte("calypr-public.ohsu.edu"))

var sha1Pool = sync.Pool{
	New: func() any {
		return sha1.New()
	},
}

var bufferPool = sync.Pool{
	New: func() any {
		return &bytes.Buffer{}
	},
}

func fastUUIDSHA1(space uuid.UUID, data []byte) string {
	h := sha1Pool.Get().(hash.Hash)
	h.Reset()
	h.Write(space[:])
	h.Write(data)
	var hashBytes [20]byte
	h.Sum(hashBytes[:0])
	sha1Pool.Put(h)

	// format uuid v5: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	// version 5 (SHA-1)
	hashBytes[6] = (hashBytes[6] & 0x0f) | 0x50
	hashBytes[8] = (hashBytes[8] & 0x3f) | 0x80

	var buf [36]byte
	hex.Encode(buf[0:8], hashBytes[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], hashBytes[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], hashBytes[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], hashBytes[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], hashBytes[10:16])

	return string(buf[:])
}

func getEdgeUUID(a, b, c string) string {
	buf := bufferPool.Get().(*bytes.Buffer)
	buf.Reset()
	buf.WriteString(a)
	buf.WriteByte('-')
	buf.WriteString(b)
	buf.WriteByte('-')
	buf.WriteString(c)
	uuidStr := fastUUIDSHA1(namespaceUUID, buf.Bytes())
	bufferPool.Put(buf)
	return uuidStr
}

func collectionID(resourceType, id string) string {
	return sanitizeKey(resourceType) + "/" + sanitizeKey(id)
}

func sanitizeKey(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "_"
	}
	needsSanitization := false
	for i := 0; i < len(value); i++ {
		r := value[i]
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') ||
			r == '_' || r == '-' || r == ':' || r == '.' || r == '@' || r == '(' || r == ')' ||
			r == '+' || r == ',' || r == '=' || r == ';' || r == '$' || r == '!' || r == '*' ||
			r == '\'' || r == '%' {
			// clean character
		} else {
			needsSanitization = true
			break
		}
	}
	if !needsSanitization {
		return value
	}

	var sb strings.Builder
	sb.Grow(len(value))
	for _, r := range value {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') ||
			r == '_' || r == '-' || r == ':' || r == '.' || r == '@' || r == '(' || r == ')' ||
			r == '+' || r == ',' || r == '=' || r == ';' || r == '$' || r == '!' || r == '*' ||
			r == '\'' || r == '%' {
			sb.WriteRune(r)
		} else {
			sb.WriteRune('_')
		}
	}
	return sb.String()
}

func splitFHIRReference(ref string) (string, string, bool) {
	firstSlash := strings.IndexByte(ref, '/')
	if firstSlash <= 0 || firstSlash == len(ref)-1 {
		return "", "", false
	}
	targetType := ref[:firstSlash]
	targetID := ref[firstSlash+1:]
	if secondSlash := strings.IndexByte(targetID, '/'); secondSlash != -1 {
		targetID = targetID[:secondSlash]
	}
	if targetID == "" {
		return "", "", false
	}
	return targetType, targetID, true
}

func buildEdgeRawJSON(key, from, to, label, projectJSON, fromType, toType string) json.RawMessage {
	var buf bytes.Buffer
	buf.Grow(256)
	buf.WriteString("{\"_key\":\"")
	buf.WriteString(key)
	buf.WriteString("\",\"_from\":\"")
	buf.WriteString(from)
	buf.WriteString("\",\"_to\":\"")
	buf.WriteString(to)
	buf.WriteString("\",\"label\":\"")
	buf.WriteString(label)
	buf.WriteString("\",\"project\":")
	buf.WriteString(projectJSON)
	buf.WriteString(",\"from_type\":\"")
	buf.WriteString(fromType)
	buf.WriteString("\",\"to_type\":\"")
	buf.WriteString(toType)
	buf.WriteString("\"}")
	return json.RawMessage(buf.Bytes())
}

`)

	var keys []string
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Keep track of which resource types are supported (those having links metadata in the schema)
	supportedResources := []string{}

	for _, k := range keys {
		def := schema.Defs[k]

		// Only concrete FHIR roots get graph loaders. Backbone definitions and
		// abstract Resource remain available to field/selector generation but
		// never become graph collections or row grains.
		if !isFHIRRootResourceDefinition(k, def) {
			continue
		}

		supportedResources = append(supportedResources, k)

		sb.WriteString(fmt.Sprintf("// ExtractEdges extracts graph links from %s.\n", k))
		sb.WriteString(fmt.Sprintf("func (x *%s) ExtractEdges(project string) ([]json.RawMessage, error) {\n", k))
		sb.WriteString("\tvar edges []json.RawMessage\n")
		sb.WriteString("\tif x == nil || x.ID == nil {\n\t\treturn edges, nil\n\t}\n")
		sb.WriteString("\tid := *x.ID\n")
		sb.WriteString("\tsourceType := \"" + k + "\"\n")
		sb.WriteString("\tprojectJSON := strconv.Quote(project)\n")
		sb.WriteString("\t_ = id\n")
		sb.WriteString("\t_ = sourceType\n")
		sb.WriteString("\t_ = projectJSON\n")
		sb.WriteString("\tvar seen map[string]struct{}\n")
		sb.WriteString("\t_ = seen\n")

		// Generate link extraction code statically!
		for _, link := range def.Links {
			ptr := link.TemplatePointers.ID
			if ptr == "" {
				continue
			}

			// We need to generate code to traverse to templatePointers
			pathParts := strings.Split(ptr, "/")[1:]
			traversalCode, err := generateTraversalCode(schema, k, pathParts, "x", k, link, "\t")
			if err != nil {
				return err
			}
			sb.WriteString(traversalCode)
		}

		sb.WriteString("\treturn edges, nil\n")
		sb.WriteString("}\n\n")
	}

	// 2. Write the unified ValidateAndExtract entrypoint
	sb.WriteString("// ValidateAndExtract parses, validates, and extracts edges for a FHIR resource.\n")
	sb.WriteString("func ValidateAndExtract(raw []byte, resourceType string, project string) (Result, error) {\n")
	sb.WriteString("\tswitch resourceType {\n")
	for _, res := range supportedResources {
		sb.WriteString(fmt.Sprintf("\tcase %q:\n", res))
		sb.WriteString(fmt.Sprintf("\t\tvar val %s\n", res))
		sb.WriteString("\t\tif err := sonic.Unmarshal(raw, &val); err != nil {\n")
		sb.WriteString("\t\t\treturn Result{}, fmt.Errorf(\"decode error: %w\", err)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tif err := val.Validate(); err != nil {\n")
		sb.WriteString("\t\t\treturn Result{}, fmt.Errorf(\"validation error: %w\", err)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tedges, err := val.ExtractEdges(project)\n")
		sb.WriteString("\t\tif err != nil {\n")
		sb.WriteString("\t\t\treturn Result{}, fmt.Errorf(\"extraction error: %w\", err)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tvar objectID string\n")
		sb.WriteString("\t\tif val.ID != nil {\n\t\t\tobjectID = *val.ID\n\t\t}\n")
		sb.WriteString("\t\treturn Result{\n")
		sb.WriteString("\t\t\tObjectID:     objectID,\n")
		sb.WriteString("\t\t\tResourceType: resourceType,\n")
		sb.WriteString("\t\t\tVertex:       json.RawMessage(raw),\n")
		sb.WriteString("\t\t\tEdges:        edges,\n")
		sb.WriteString("\t\t}, nil\n")
	}
	sb.WriteString("\tdefault:\n")
	sb.WriteString("\t\treturn Result{}, fmt.Errorf(\"unsupported resource type %s\", resourceType)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func generateTraversalCode(schema *Schema, structName string, path []string, varName string, currentType string, link Link, indent string) (string, error) {
	if len(path) == 0 {
		// We have reached the string value (the reference).
		// We emit the edge building code!
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("%srefVal := %s\n", indent, varName))
		sb.WriteString(fmt.Sprintf("%srefType, targetID, ok := splitFHIRReference(refVal)\n", indent))
		sb.WriteString(fmt.Sprintf("%sif ok {\n", indent))
		sb.WriteString(fmt.Sprintf("%s\trefType, ok = fhirschema.ConcreteResourceType(refType)\n", indent))
		sb.WriteString(fmt.Sprintf("%s\tif ok {\n", indent))

		// Match prefix check
		allowAnyMatch := false
		matchPrefix := ""
		for _, rx := range link.TargetHints.RegexMatch {
			if rx == "Resource/*" {
				allowAnyMatch = true
			} else {
				matchPrefix = strings.TrimSuffix(rx, "/*")
			}
		}

		bodyIndent := indent + "\t\t"
		if !allowAnyMatch && matchPrefix != "" {
			sb.WriteString(fmt.Sprintf("%sif refType == %q {\n", bodyIndent, matchPrefix))
			bodyIndent += "\t"
		}

		sb.WriteString(fmt.Sprintf("%sforwardKey := getEdgeUUID(targetID, id, %q)\n", bodyIndent, link.Rel))
		sb.WriteString(fmt.Sprintf("%sif seen == nil {\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\tseen = make(map[string]struct{}, 4)\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%sif _, exists := seen[forwardKey]; !exists {\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\tseen[forwardKey] = struct{}{}\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\tedges = append(edges, buildEdgeRawJSON(\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tforwardKey,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(sourceType, id),\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(refType, targetID),\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\t%q,\n", bodyIndent, link.Rel))
		sb.WriteString(fmt.Sprintf("%s\t\tprojectJSON,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\tsourceType,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t\trefType,\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s\t))\n", bodyIndent))
		sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))

		// Check if backref exists
		if len(link.TargetHints.Backref) > 0 && link.TargetHints.Backref[0] != "" {
			backref := link.TargetHints.Backref[0]
			sb.WriteString(fmt.Sprintf("%sbackrefKey := getEdgeUUID(id, targetID, %q)\n", bodyIndent, backref))
			sb.WriteString(fmt.Sprintf("%sif seen == nil {\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\tseen = make(map[string]struct{}, 4)\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%sif _, exists := seen[backrefKey]; !exists {\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\tseen[backrefKey] = struct{}{}\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\tedges = append(edges, buildEdgeRawJSON(\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tbackrefKey,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(refType, targetID),\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tcollectionID(sourceType, id),\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\t%q,\n", bodyIndent, backref))
			sb.WriteString(fmt.Sprintf("%s\t\tprojectJSON,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\trefType,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t\tsourceType,\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s\t))\n", bodyIndent))
			sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
		}

		if !allowAnyMatch && matchPrefix != "" {
			bodyIndent = bodyIndent[:len(bodyIndent)-1]
			sb.WriteString(fmt.Sprintf("%s}\n", bodyIndent))
		}

		sb.WriteString(fmt.Sprintf("%s\t}\n", indent))
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
		return sb.String(), nil
	}

	part := path[0]

	if part == "-" {
		// VarName must be a slice. Loop over the elements.
		// Wait, what is the item type?
		// We need to look up the parent property to see what its items are.
		// E.g. x.PartOf which is a slice. Let's find what the element type is.
		// We can pass currentType down, but since we are iterating, we need to know the type of items.
		// Let's pass the element type in currentType.
		// If part is "-", then the type of item is currentType.
		loopVar := fmt.Sprintf("item_%d_%s", len(path), strings.ReplaceAll(varName, ".", "_"))
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("%sfor _, %s := range %s {\n", indent, loopVar, varName))
		// Check for nil if item is a pointer
		sb.WriteString(fmt.Sprintf("%s\tif %s != nil {\n", indent+"\t", loopVar))
		subCode, err := generateTraversalCode(schema, structName, path[1:], loopVar, currentType, link, indent+"\t\t")
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
		sb.WriteString(fmt.Sprintf("%s\t}\n", indent))
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
		return sb.String(), nil
	}

	// It's a field name!
	// Look up in schema Defs[currentType] to find property named `part`.
	def, ok := schema.Defs[currentType]
	if !ok {
		return "", fmt.Errorf("definition %s not found in schema while resolving path part %s", currentType, part)
	}

	prop, ok := def.Properties[part]
	if !ok {
		// It could be that part is not a direct property, or it is in some other way.
		// But in graph-fhir.json, they are always properties.
		return "", fmt.Errorf("property %s not found in definition %s", part, currentType)
	}

	fieldName := toGoName(part)
	nextVarName := fmt.Sprintf("%s.%s", varName, fieldName)

	var nextType string
	if prop.Ref != "" {
		nextType = refName(prop.Ref)
	} else if prop.Items != nil && prop.Items.Ref != "" {
		nextType = refName(prop.Items.Ref)
	} else if typeStr, ok := prop.Type.(string); ok && typeStr == "string" {
		nextType = "string"
	}

	var sb strings.Builder
	// If it's a pointer type, check for nil
	goType := getGoType(prop, true) // treat as optional to see if it has pointer prefix
	isPointer := strings.HasPrefix(goType, "*")
	isSlice := strings.HasPrefix(goType, "[]")

	if isPointer {
		sb.WriteString(fmt.Sprintf("%sif %s != nil {\n", indent, nextVarName))
		// If it's a leaf string pointer (like *string), dereference it
		actualVar := nextVarName
		if nextType == "string" {
			actualVar = "*" + nextVarName
		}
		subCode, err := generateTraversalCode(schema, structName, path[1:], actualVar, nextType, link, indent+"\t")
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
	} else if isSlice {
		sb.WriteString(fmt.Sprintf("%sif %s != nil {\n", indent, nextVarName))
		subCode, err := generateTraversalCode(schema, structName, path[1:], nextVarName, nextType, link, indent+"\t")
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
	} else {
		subCode, err := generateTraversalCode(schema, structName, path[1:], nextVarName, nextType, link, indent)
		if err != nil {
			return "", err
		}
		sb.WriteString(subCode)
	}

	return sb.String(), nil
}
