package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"
)

// generateFHIRGraphQL emits the generated half of Loom's GraphQL schema. It
// deliberately contains only schema declarations: resolver behavior remains
// in the generic FHIR query service and the handwritten Query schema.
//
// The graph-fhir document has 136 definitions, including backbone and
// datatype definitions. Emitting all of them (rather than only concrete root
// resources) makes every JSON property selectable in a typed GraphQL query.
func generateFHIRGraphQL(schema *Schema, path string) error {
	if schema == nil {
		return fmt.Errorf("nil FHIR schema")
	}

	defs := make([]string, 0, len(schema.Defs))
	for name := range schema.Defs {
		if !isGraphQLName(name) {
			return fmt.Errorf("definition %q is not a legal GraphQL name", name)
		}
		switch name {
		case "FHIRResource", "FHIRResourceType", "Long", "Query":
			return fmt.Errorf("definition %q collides with generated GraphQL name", name)
		}
		defs = append(defs, name)
	}
	sort.Strings(defs)
	roots := schemaFHIRRootResourceTypes(schema)
	if len(roots) == 0 {
		return fmt.Errorf("FHIR schema has no concrete resource definitions")
	}
	seenRoots := make(map[string]struct{}, len(roots))
	seenEnumValues := make(map[string]string, len(roots))
	for _, root := range roots {
		if _, exists := seenRoots[root]; exists {
			return fmt.Errorf("duplicate FHIR root resource %q", root)
		}
		seenRoots[root] = struct{}{}
		enumValue := fhirEnumValue(root)
		if previous, exists := seenEnumValues[enumValue]; exists {
			return fmt.Errorf("FHIR resource enum value %q collides for %q and %q", enumValue, previous, root)
		}
		seenEnumValues[enumValue] = root
	}
	if err := validateFHIRGraphQLRefs(schema); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	b.WriteString("# This document is loaded alongside graphqlapi/schema.graphqls by gqlgen.\n\n")
	b.WriteString("scalar Long\n\n")
	// gqlgen normally derives resolver method names from GraphQL field names.
	// The FHIR primitive-extension convention intentionally has both `code` and
	// `_code`; @goField keeps those two legal Go identifiers distinct while
	// leaving the public JSON/GraphQL names untouched.
	b.WriteString("directive @goField(forceResolver: Boolean, name: String, omittable: Boolean, type: String) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION\n\n")
	b.WriteString("interface FHIRResource {\n")
	b.WriteString("  id: ID!\n")
	b.WriteString("  resourceType: String!\n")
	b.WriteString("}\n\n")
	b.WriteString("enum FHIRResourceType {\n")
	for _, root := range roots {
		b.WriteString("  ")
		b.WriteString(fhirEnumValue(root))
		b.WriteByte('\n')
	}
	b.WriteString("}\n\n")

	// Root operations use exact JSON Schema definition capitalization. These
	// are extensions because Query itself is declared by the handwritten API.
	b.WriteString("extend type Query {\n")
	for _, root := range roots {
		b.WriteString("  ")
		b.WriteString(root)
		b.WriteString("(project: String!, filters: [FhirFilterInput!] = [], limit: Int = 25): [")
		b.WriteString(root)
		b.WriteString("!]!\n")
	}
	b.WriteString("}\n\n")

	for _, name := range defs {
		def := schema.Defs[name]
		if def == nil {
			return fmt.Errorf("definition %q is null", name)
		}
		b.WriteString("type ")
		b.WriteString(name)
		for _, root := range roots {
			if root == name {
				b.WriteString(" implements FHIRResource")
				break
			}
		}
		b.WriteString(" {\n")

		props := make([]string, 0, len(def.Properties))
		for propName := range def.Properties {
			if propName == "links" {
				continue
			}
			if !isGraphQLName(propName) {
				return fmt.Errorf("property %q on %q is not a legal GraphQL name", propName, name)
			}
			props = append(props, propName)
		}
		sort.Strings(props)
		for _, propName := range props {
			prop := def.Properties[propName]
			fieldType, err := graphqlPropertyType(name, propName, prop, seenRoots)
			if err != nil {
				return err
			}
			b.WriteString("  ")
			b.WriteString(propName)
			b.WriteString(": ")
			b.WriteString(fieldType)
			if strings.HasPrefix(propName, "_") {
				b.WriteString(" @goField(name: \"")
				b.WriteString(toGoName(propName))
				b.WriteString("\")")
			}
			b.WriteByte('\n')
		}
		if name == "Reference" {
			if _, exists := def.Properties["resource"]; exists {
				return fmt.Errorf("Reference.resource property collides with generated resolver field")
			}
			b.WriteString("  resource(type: FHIRResourceType, optional: Boolean! = false): FHIRResource\n")
		}
		b.WriteString("}\n\n")
	}

	return os.WriteFile(path, []byte(b.String()), 0644)
}

func isGraphQLName(name string) bool {
	if name == "" {
		return false
	}
	for i, r := range name {
		if i == 0 {
			if r != '_' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

func fhirEnumValue(resourceType string) string {
	var b strings.Builder
	runes := []rune(resourceType)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) && (unicode.IsLower(runes[i-1]) || (i+1 < len(runes) && unicode.IsLower(runes[i+1]))) {
			b.WriteByte('_')
		}
		if r == '-' || r == ' ' {
			b.WriteByte('_')
			continue
		}
		b.WriteRune(unicode.ToUpper(r))
	}
	return b.String()
}

func graphqlPropertyType(owner, name string, prop *Property, roots map[string]struct{}) (string, error) {
	if prop == nil {
		return "JSON", nil
	}
	if name == "fhir_comments" {
		// graph-fhir permits a string or an array. The runtime normalizes both
		// forms to a string list before decoding.
		return "[String!]", nil
	}
	if prop.Ref != "" {
		ref := refName(prop.Ref)
		if ref == "links" {
			return "JSON", nil
		}
		if !isGraphQLName(ref) {
			return "", fmt.Errorf("$ref %q on %q.%s resolves to invalid GraphQL name", prop.Ref, owner, name)
		}
		return ref, nil
	}
	if prop.Items != nil {
		item, err := graphqlPropertyType(owner, name, prop.Items, roots)
		if err != nil {
			return "", err
		}
		// Arrays in the source schema are nullable; item schemas are concrete
		// unless JSON Schema explicitly allows null (not present in this FHIR
		// profile).
		return "[" + strings.TrimSuffix(item, "!") + "!]", nil
	}
	typeName, err := graphqlSchemaType(prop.Type)
	if err != nil {
		return "", fmt.Errorf("unsupported property shape on %q.%s: %w", owner, name, err)
	}
	switch typeName {
	case "string":
		if _, ok := roots[owner]; ok && name == "id" {
			return "ID!", nil
		}
		if _, ok := roots[owner]; ok && name == "resourceType" {
			return "String!", nil
		}
		return "String", nil
	case "boolean":
		return "Boolean", nil
	case "number":
		return "Float", nil
	case "integer":
		return "Long", nil
	case "object":
		return "JSON", nil
	case "array":
		return "[JSON!]", nil
	case "":
		// fhir_comments is handled above. Other typeless values are free-form
		// objects in graph-fhir and intentionally use the existing JSON scalar.
		return "JSON", nil
	default:
		return "", fmt.Errorf("unsupported JSON Schema type %q on %q.%s", typeName, owner, name)
	}
}

func graphqlSchemaType(value any) (string, error) {
	switch typed := value.(type) {
	case nil:
		return "", nil
	case string:
		return typed, nil
	case []any:
		var selected string
		for _, member := range typed {
			name, ok := member.(string)
			if !ok {
				return "", fmt.Errorf("type union member %T is not a string", member)
			}
			if name == "null" {
				continue
			}
			if selected != "" && selected != name {
				return "", fmt.Errorf("type union %q and %q is not representable", selected, name)
			}
			selected = name
		}
		return selected, nil
	default:
		return "", fmt.Errorf("type value %T is not supported", value)
	}
}

func validateFHIRGraphQLRefs(schema *Schema) error {
	for owner, def := range schema.Defs {
		if def == nil {
			continue
		}
		for name, prop := range def.Properties {
			if err := validateFHIRGraphQLPropertyRef(schema, owner, name, prop); err != nil {
				return err
			}
		}
	}
	return nil
}

func validateFHIRGraphQLPropertyRef(schema *Schema, owner, name string, prop *Property) error {
	if prop == nil {
		return nil
	}
	if prop.Ref != "" {
		ref := refName(prop.Ref)
		if ref != "links" {
			if _, ok := schema.Defs[ref]; !ok {
				return fmt.Errorf("$ref %q on %q.%s does not resolve to a schema definition", prop.Ref, owner, name)
			}
		}
	}
	if prop.Items != nil {
		return validateFHIRGraphQLPropertyRef(schema, owner, name+"[]", prop.Items)
	}
	for childName, child := range prop.Properties {
		if err := validateFHIRGraphQLPropertyRef(schema, owner, name+"."+childName, child); err != nil {
			return err
		}
	}
	return nil
}
