package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

func generateFHIRSchema(schema *Schema, path string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	sb.WriteString("package fhirschema\n\n")
	sb.WriteString("type Definition struct {\n\tTitle string\n\tDescription string\n\tRequired []string\n\tProperties []Property\n}\n\n")
	sb.WriteString("type Property struct {\n\tName string\n\tKind string\n\tFormat string\n\tRef string\n\tProperties []Property\n\tItemKind string\n\tItemFormat string\n\tItemRef string\n\tItemProperties []Property\n\tChoiceGroup string\n\tChoiceGroupRequired bool\n\tElementRequired bool\n\tRequiredChildren []string\n\tBindingStrength string\n\tBindingURI string\n\tBindingVersion string\n\tBindingDescription string\n\tReferenceTargetTypes []string\n\tTitle string\n\tDescription string\n}\n\n")
	sb.WriteString("type Traversal struct {\n\tFromType string\n\tEdgeLabel string\n\tToType string\n\tDirection []string\n\tMultiplicity []string\n\tBackref []string\n\tRegexMatch []string\n}\n\n")
	sb.WriteString("var ResourceTypes = []string{\n")
	for _, k := range schemaFHIRRootResourceTypes(schema) {
		sb.WriteString(fmt.Sprintf("\t%q,\n", k))
	}
	sb.WriteString("}\n\n")
	sb.WriteString("var Definitions = map[string]Definition{\n")
	var keys []string
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("\t%q: {\n", k))
		def := schema.Defs[k]
		if def.Title != "" {
			sb.WriteString(fmt.Sprintf("\t\tTitle: %q,\n", def.Title))
		}
		if def.Description != "" {
			sb.WriteString(fmt.Sprintf("\t\tDescription: %q,\n", def.Description))
		}
		if len(def.Required) > 0 {
			writeGeneratedStringSlice(&sb, "Required", def.Required, 2)
		}
		sb.WriteString("\t\tProperties: []Property{\n")
		writeGeneratedProperties(&sb, schema, def.Properties, 3)
		sb.WriteString("\t\t},\n")
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n\n")
	sb.WriteString("var Traversals = map[string]Traversal{\n")
	seenTraversalKeys := map[string]struct{}{}
	for _, k := range keys {
		def := schema.Defs[k]
		if !isFHIRRootResourceDefinition(k, def) {
			continue
		}
		writeLink := func(link Link, compact bool) {
			toType, ok := schemaConcreteLinkTargetType(schema, link)
			if strings.TrimSpace(link.Rel) == "" || !ok {
				return
			}
			forwardKey := traversalKey(k, link.Rel, toType)
			if _, ok := seenTraversalKeys[forwardKey]; !ok {
				if compact {
					writeGeneratedTraversalCompact(&sb, k, link.Rel, toType, link, forwardKey)
				} else {
					writeGeneratedTraversal(&sb, k, link.Rel, toType, link, forwardKey)
				}
				seenTraversalKeys[forwardKey] = struct{}{}
			}
			reverseKey := traversalKey(toType, link.Rel, k)
			if _, ok := seenTraversalKeys[reverseKey]; !ok {
				if compact {
					writeGeneratedTraversalCompact(&sb, toType, link.Rel, k, link, reverseKey)
				} else {
					writeGeneratedTraversal(&sb, toType, link.Rel, k, link, reverseKey)
				}
				seenTraversalKeys[reverseKey] = struct{}{}
			}
			for _, backref := range link.TargetHints.Backref {
				backrefKey := traversalKey(toType, backref, k)
				if strings.TrimSpace(backref) == "" {
					continue
				}
				if _, ok := seenTraversalKeys[backrefKey]; ok {
					continue
				}
				if compact {
					writeGeneratedTraversalCompact(&sb, toType, backref, k, link, backrefKey)
				} else {
					writeGeneratedTraversal(&sb, toType, backref, k, link, backrefKey)
				}
				seenTraversalKeys[backrefKey] = struct{}{}
			}
		}
		for _, link := range def.Links {
			writeLink(link, false)
		}
		for _, link := range schemaNestedLinkDefinitions(schema, k) {
			writeLink(link, true)
		}
	}
	sb.WriteString("}\n")
	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func schemaNestedLinkDefinitions(schema *Schema, rootType string) []Link {
	root := schema.Defs[rootType]
	if root == nil {
		return nil
	}
	active := map[string]bool{}
	var links []Link
	var visitDefinition func(string, string)
	visitDefinition = func(typeName, path string) {
		definition := schema.Defs[typeName]
		if definition == nil || isFHIRRootResourceDefinition(typeName, definition) {
			return
		}
		if active[typeName] {
			return
		}
		active[typeName] = true
		defer delete(active, typeName)
		prefix := nestedTraversalPathPrefix(path)
		for _, link := range definition.Links {
			link.Rel = nestedTraversalLabel(prefix, link.Rel)
			link.TargetHints.Backref = append([]string(nil), link.TargetHints.Backref...)
			for index, backref := range link.TargetHints.Backref {
				link.TargetHints.Backref[index] = nestedTraversalLabel(prefix, backref)
			}
			links = append(links, link)
		}
		return
	}
	propertyNames := make([]string, 0, len(root.Properties))
	for name := range root.Properties {
		propertyNames = append(propertyNames, name)
	}
	sort.Strings(propertyNames)
	for _, name := range propertyNames {
		property := root.Properties[name]
		if property == nil {
			continue
		}
		if property.Ref != "" {
			visitDefinition(refName(property.Ref), name)
		}
		if property.Items != nil && property.Items.Ref != "" {
			visitDefinition(refName(property.Items.Ref), name+"[]")
		}
	}
	return links
}

func nestedTraversalPathPrefix(path string) string {
	path = strings.ReplaceAll(path, "[]", "")
	return strings.ReplaceAll(path, ".", "_")
}

func nestedTraversalLabel(prefix, relation string) string {
	if prefix == "" {
		return relation
	}
	return prefix + "_" + relation
}

// schemaConcreteLinkTargetType resolves a graph link target from schema
// semantics. Relationship labels are only a compatibility fallback for older
// schema entries; the fallback is accepted only when it resolves to a
// concrete root, so labels can never introduce a graph node by themselves.
func schemaConcreteLinkTargetType(schema *Schema, link Link) (string, bool) {
	candidates := []string{refName(link.TargetSchema.Ref)}
	if candidates[0] == "" {
		for _, regex := range link.TargetHints.RegexMatch {
			candidate := strings.TrimSuffix(strings.TrimSpace(regex), "/*")
			if candidate != "" {
				candidates = append(candidates, candidate)
			}
		}
		candidates = append(candidates, targetTypeFromLabel(link.Rel))
	}
	for _, candidate := range candidates {
		candidate = strings.TrimSpace(candidate)
		if candidate == "" {
			continue
		}
		if isFHIRRootResourceDefinition(candidate, schema.Defs[candidate]) {
			return candidate, true
		}
	}
	return "", false
}

// schemaFHIRRootResourceTypes discovers compiler-visible collections from the
// checked-in graph schema. It deliberately does not carry a copied list of
// FHIR resource names: a schema definition is a concrete root only when its
// own resourceType constant names that definition and it has the FHIR Resource
// root fields (a string id plus an explicit metadata object).
//
// The graph schema also publishes the abstract Resource base definition so
// generated field references can resolve. Its resourceType constant is the
// generic "Resource" placeholder rather than a concrete graph collection, so
// it is excluded by role rather than maintaining a list of concrete types.
func schemaFHIRRootResourceTypes(schema *Schema) []string {
	if schema == nil {
		return nil
	}

	keys := make([]string, 0, len(schema.Defs))
	for name := range schema.Defs {
		keys = append(keys, name)
	}
	sort.Strings(keys)

	roots := make([]string, 0, len(keys))
	for _, name := range keys {
		if isFHIRRootResourceDefinition(name, schema.Defs[name]) {
			roots = append(roots, name)
		}
	}
	return roots
}

func isFHIRRootResourceDefinition(name string, def *Definition) bool {
	name = strings.TrimSpace(name)
	if name == "" || def == nil {
		return false
	}

	resourceType, ok := stringConstant(def.Properties["resourceType"])
	if !ok || resourceType != name {
		return false
	}
	if resourceType == "Resource" {
		return false
	}

	id := def.Properties["id"]
	if id == nil || propertyType(id) != "string" {
		return false
	}
	meta := def.Properties["meta"]
	return meta != nil && strings.TrimSpace(meta.Ref) != ""
}

func stringConstant(prop *Property) (string, bool) {
	if prop == nil {
		return "", false
	}
	value, ok := prop.Const.(string)
	value = strings.TrimSpace(value)
	return value, ok && value != ""
}

func propertyType(prop *Property) string {
	if prop == nil {
		return ""
	}
	if prop.Ref != "" {
		return "object"
	}
	if typeStr, ok := prop.Type.(string); ok {
		return typeStr
	}
	if prop.Items != nil {
		return "array"
	}
	if len(prop.Properties) > 0 {
		return "object"
	}
	return ""
}

func writeGeneratedProperties(sb *strings.Builder, schema *Schema, props map[string]*Property, indent int) {
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		prop := props[k]
		if prop == nil {
			continue
		}
		writeIndent(sb, indent)
		sb.WriteString("{\n")
		writeIndent(sb, indent+1)
		sb.WriteString(fmt.Sprintf("Name: %q,\n", k))
		writeIndent(sb, indent+1)
		sb.WriteString(fmt.Sprintf("Kind: %q,\n", propertyType(prop)))
		if prop.Format != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("Format: %q,\n", prop.Format))
		}
		if ref := schemaDefinitionRefName(schema, prop.Ref); ref != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("Ref: %q,\n", ref))
		}
		if prop.ChoiceGroup != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("ChoiceGroup: %q,\n", prop.ChoiceGroup))
		}
		if prop.ChoiceGroupRequired {
			writeIndent(sb, indent+1)
			sb.WriteString("ChoiceGroupRequired: true,\n")
		}
		if prop.ElementRequired {
			writeIndent(sb, indent+1)
			sb.WriteString("ElementRequired: true,\n")
		}
		if len(prop.Required) > 0 {
			writeGeneratedStringSlice(sb, "RequiredChildren", prop.Required, indent+1)
		}
		if prop.BindingStrength != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("BindingStrength: %q,\n", prop.BindingStrength))
		}
		if prop.BindingURI != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("BindingURI: %q,\n", prop.BindingURI))
		}
		if prop.BindingVersion != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("BindingVersion: %q,\n", prop.BindingVersion))
		}
		if prop.BindingDescription != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("BindingDescription: %q,\n", prop.BindingDescription))
		}
		if len(prop.ReferenceTargetTypes) > 0 {
			writeGeneratedStringSlice(sb, "ReferenceTargetTypes", prop.ReferenceTargetTypes, indent+1)
		}
		if prop.Title != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("Title: %q,\n", prop.Title))
		}
		if prop.Description != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("Description: %q,\n", prop.Description))
		}
		if prop.Items != nil {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("ItemKind: %q,\n", propertyType(prop.Items)))
			if prop.Items.Format != "" {
				writeIndent(sb, indent+1)
				sb.WriteString(fmt.Sprintf("ItemFormat: %q,\n", prop.Items.Format))
			}
			if ref := schemaDefinitionRefName(schema, prop.Items.Ref); ref != "" {
				writeIndent(sb, indent+1)
				sb.WriteString(fmt.Sprintf("ItemRef: %q,\n", ref))
			}
			if len(prop.Items.Properties) > 0 {
				writeIndent(sb, indent+1)
				sb.WriteString("ItemProperties: []Property{\n")
				writeGeneratedProperties(sb, schema, prop.Items.Properties, indent+2)
				writeIndent(sb, indent+1)
				sb.WriteString("},\n")
			}
		}
		if len(prop.Properties) > 0 {
			writeIndent(sb, indent+1)
			sb.WriteString("Properties: []Property{\n")
			writeGeneratedProperties(sb, schema, prop.Properties, indent+2)
			writeIndent(sb, indent+1)
			sb.WriteString("},\n")
		}
		writeIndent(sb, indent)
		sb.WriteString("},\n")
	}
}

func schemaDefinitionRefName(schema *Schema, ref string) string {
	if schema == nil || schema.ID == "" || ref == "" {
		return ""
	}
	prefix := strings.TrimRight(schema.ID, "/") + "/"
	if !strings.HasPrefix(ref, prefix) {
		return ""
	}
	name := strings.TrimPrefix(ref, prefix)
	if name == "" || strings.Contains(name, "/") {
		return ""
	}
	return name
}

func writeGeneratedStringSlice(sb *strings.Builder, fieldName string, values []string, indent int) {
	writeIndent(sb, indent)
	sb.WriteString(fieldName)
	sb.WriteString(": []string{")
	if len(values) == 0 {
		sb.WriteString("},\n")
		return
	}
	sb.WriteString("\n")
	for _, value := range values {
		writeIndent(sb, indent+1)
		sb.WriteString(fmt.Sprintf("%q,\n", value))
	}
	writeIndent(sb, indent)
	sb.WriteString("},\n")
}

func traversalKey(fromType, edgeLabel, toType string) string {
	return fromType + "|" + edgeLabel + "|" + toType
}

func writeGeneratedTraversal(sb *strings.Builder, fromType, edgeLabel, toType string, link Link, key string) {
	sb.WriteString(fmt.Sprintf("\t%q: {\n", key))
	sb.WriteString(fmt.Sprintf("\t\tFromType: %q,\n", fromType))
	sb.WriteString(fmt.Sprintf("\t\tEdgeLabel: %q,\n", edgeLabel))
	sb.WriteString(fmt.Sprintf("\t\tToType: %q,\n", toType))
	writeGeneratedStringSlice(sb, "Direction", link.TargetHints.Direction, 2)
	writeGeneratedStringSlice(sb, "Multiplicity", link.TargetHints.Multiplicity, 2)
	writeGeneratedStringSlice(sb, "Backref", link.TargetHints.Backref, 2)
	writeGeneratedStringSlice(sb, "RegexMatch", link.TargetHints.RegexMatch, 2)
	sb.WriteString("\t},\n")
}

func writeGeneratedTraversalCompact(sb *strings.Builder, fromType, edgeLabel, toType string, link Link, key string) {
	sb.WriteString(fmt.Sprintf("\t%q: {FromType: %q, EdgeLabel: %q, ToType: %q", key, fromType, edgeLabel, toType))
	writeGeneratedInlineStringSlice(sb, "Direction", link.TargetHints.Direction)
	writeGeneratedInlineStringSlice(sb, "Multiplicity", link.TargetHints.Multiplicity)
	writeGeneratedInlineStringSlice(sb, "Backref", link.TargetHints.Backref)
	writeGeneratedInlineStringSlice(sb, "RegexMatch", link.TargetHints.RegexMatch)
	sb.WriteString("},\n")
}

func writeGeneratedInlineStringSlice(sb *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		return
	}
	sb.WriteString(", " + field + ": []string{")
	for index, value := range values {
		if index > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(fmt.Sprintf("%q", value))
	}
	sb.WriteString("}")
}

func writeIndent(sb *strings.Builder, n int) {
	for i := 0; i < n; i++ {
		sb.WriteString("\t")
	}
}
