package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

func generateFHIRSchema(schema *Schema, path string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	sb.WriteString("package fhirschema\n\n")
	sb.WriteString("type Definition struct { Properties []Property }\n\n")
	sb.WriteString("type Property struct {\n\tName string\n\tKind string\n\tFormat string\n\tRef string\n\tProperties []Property\n\tItemKind string\n\tItemFormat string\n\tItemRef string\n\tItemProperties []Property\n}\n\n")
	sb.WriteString("type Traversal struct {\n\tFromType string\n\tEdgeLabel string\n\tToType string\n\tDirection []string\n\tMultiplicity []string\n\tBackref []string\n\tRegexMatch []string\n}\n\n")
	sb.WriteString("var ResourceTypes = []string{\n")
	for _, k := range schemaFHIRRootResourceTypes(schema) {
		sb.WriteString(fmt.Sprintf("\t%q,\n", k))
	}
	sb.WriteString("}\n\n")
	sb.WriteString("var Definitions = map[string]Definition{\n")
	var keys []string
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("\t%q: {\n", k))
		sb.WriteString("\t\tProperties: []Property{\n")
		writeGeneratedProperties(&sb, schema.Defs[k].Properties, 3)
		sb.WriteString("\t\t},\n")
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n\n")
	sb.WriteString("var Traversals = map[string]Traversal{\n")
	seenTraversalKeys := map[string]struct{}{}
	for _, k := range keys {
		def := schema.Defs[k]
		if def == nil || len(def.Links) == 0 {
			continue
		}
		for _, link := range def.Links {
			toType := refName(link.TargetSchema.Ref)
			if strings.TrimSpace(toType) == "" {
				toType = targetTypeFromLabel(link.Rel)
			}
			if strings.TrimSpace(link.Rel) == "" || strings.TrimSpace(toType) == "" {
				continue
			}
			forwardKey := traversalKey(k, link.Rel, toType)
			if _, ok := seenTraversalKeys[forwardKey]; !ok {
				writeGeneratedTraversal(&sb, k, link.Rel, toType, link, forwardKey)
				seenTraversalKeys[forwardKey] = struct{}{}
			}
			reverseKey := traversalKey(toType, link.Rel, k)
			if _, ok := seenTraversalKeys[reverseKey]; !ok {
				writeGeneratedTraversal(&sb, toType, link.Rel, k, link, reverseKey)
				seenTraversalKeys[reverseKey] = struct{}{}
			}
		}
	}
	sb.WriteString("}\n")
	return os.WriteFile(path, []byte(sb.String()), 0644)
}

// schemaFHIRRootResourceTypes discovers compiler-visible collections from the
// checked-in graph schema. It deliberately does not carry a copied list of
// FHIR resource names: a schema definition is a concrete root only when its
// own resourceType constant names that definition and it has the FHIR Resource
// root fields (a string id plus an explicit metadata object).
//
// The graph schema also publishes the abstract Resource base definition so
// generated field references can resolve. Its resourceType constant is the
// generic "Resource" placeholder rather than a concrete graph collection, so
// it is excluded by role rather than maintaining a list of concrete types.
func schemaFHIRRootResourceTypes(schema *Schema) []string {
	if schema == nil {
		return nil
	}

	keys := make([]string, 0, len(schema.Defs))
	for name := range schema.Defs {
		keys = append(keys, name)
	}
	sort.Strings(keys)

	roots := make([]string, 0, len(keys))
	for _, name := range keys {
		if isFHIRRootResourceDefinition(name, schema.Defs[name]) {
			roots = append(roots, name)
		}
	}
	return roots
}

func isFHIRRootResourceDefinition(name string, def *Definition) bool {
	name = strings.TrimSpace(name)
	if name == "" || def == nil {
		return false
	}

	resourceType, ok := stringConstant(def.Properties["resourceType"])
	if !ok || resourceType != name {
		return false
	}
	if resourceType == "Resource" {
		return false
	}

	id := def.Properties["id"]
	if id == nil || propertyType(id) != "string" {
		return false
	}
	meta := def.Properties["meta"]
	return meta != nil && strings.TrimSpace(meta.Ref) != ""
}

func stringConstant(prop *Property) (string, bool) {
	if prop == nil {
		return "", false
	}
	value, ok := prop.Const.(string)
	value = strings.TrimSpace(value)
	return value, ok && value != ""
}

func propertyType(prop *Property) string {
	if prop == nil {
		return ""
	}
	if prop.Ref != "" {
		return "object"
	}
	if typeStr, ok := prop.Type.(string); ok {
		return typeStr
	}
	if prop.Items != nil {
		return "array"
	}
	if len(prop.Properties) > 0 {
		return "object"
	}
	return ""
}

func writeGeneratedProperties(sb *strings.Builder, props map[string]*Property, indent int) {
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		prop := props[k]
		if prop == nil {
			continue
		}
		writeIndent(sb, indent)
		sb.WriteString("{\n")
		writeIndent(sb, indent+1)
		sb.WriteString(fmt.Sprintf("Name: %q,\n", k))
		writeIndent(sb, indent+1)
		sb.WriteString(fmt.Sprintf("Kind: %q,\n", propertyType(prop)))
		if prop.Format != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("Format: %q,\n", prop.Format))
		}
		if prop.Ref != "" {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("Ref: %q,\n", refName(prop.Ref)))
		}
		if prop.Items != nil {
			writeIndent(sb, indent+1)
			sb.WriteString(fmt.Sprintf("ItemKind: %q,\n", propertyType(prop.Items)))
			if prop.Items.Format != "" {
				writeIndent(sb, indent+1)
				sb.WriteString(fmt.Sprintf("ItemFormat: %q,\n", prop.Items.Format))
			}
			if prop.Items.Ref != "" {
				writeIndent(sb, indent+1)
				sb.WriteString(fmt.Sprintf("ItemRef: %q,\n", refName(prop.Items.Ref)))
			}
			if len(prop.Items.Properties) > 0 {
				writeIndent(sb, indent+1)
				sb.WriteString("ItemProperties: []Property{\n")
				writeGeneratedProperties(sb, prop.Items.Properties, indent+2)
				writeIndent(sb, indent+1)
				sb.WriteString("},\n")
			}
		}
		if len(prop.Properties) > 0 {
			writeIndent(sb, indent+1)
			sb.WriteString("Properties: []Property{\n")
			writeGeneratedProperties(sb, prop.Properties, indent+2)
			writeIndent(sb, indent+1)
			sb.WriteString("},\n")
		}
		writeIndent(sb, indent)
		sb.WriteString("},\n")
	}
}

func writeGeneratedStringSlice(sb *strings.Builder, fieldName string, values []string, indent int) {
	writeIndent(sb, indent)
	sb.WriteString(fieldName)
	sb.WriteString(": []string{")
	if len(values) == 0 {
		sb.WriteString("},\n")
		return
	}
	sb.WriteString("\n")
	for _, value := range values {
		writeIndent(sb, indent+1)
		sb.WriteString(fmt.Sprintf("%q,\n", value))
	}
	writeIndent(sb, indent)
	sb.WriteString("},\n")
}

func traversalKey(fromType, edgeLabel, toType string) string {
	return fromType + "|" + edgeLabel + "|" + toType
}

func writeGeneratedTraversal(sb *strings.Builder, fromType, edgeLabel, toType string, link Link, key string) {
	sb.WriteString(fmt.Sprintf("\t%q: {\n", key))
	sb.WriteString(fmt.Sprintf("\t\tFromType: %q,\n", fromType))
	sb.WriteString(fmt.Sprintf("\t\tEdgeLabel: %q,\n", edgeLabel))
	sb.WriteString(fmt.Sprintf("\t\tToType: %q,\n", toType))
	writeGeneratedStringSlice(sb, "Direction", link.TargetHints.Direction, 2)
	writeGeneratedStringSlice(sb, "Multiplicity", link.TargetHints.Multiplicity, 2)
	writeGeneratedStringSlice(sb, "Backref", link.TargetHints.Backref, 2)
	writeGeneratedStringSlice(sb, "RegexMatch", link.TargetHints.RegexMatch, 2)
	sb.WriteString("\t},\n")
}

func writeIndent(sb *strings.Builder, n int) {
	for i := 0; i < n; i++ {
		sb.WriteString("\t")
	}
}
