package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

func getGoType(prop *Property, isField bool) string {
	if prop.Ref != "" {
		name := refName(prop.Ref)
		if name == "links" {
			return "[]any"
		}
		return "*" + name
	}

	// Check for fhir_comments which is anyOf [string, array of string]
	if prop.Type == nil && prop.Items == nil && prop.Ref == "" {
		return "FHIRComments"
	}

	typeStr, ok := prop.Type.(string)
	if !ok {
		return "any"
	}

	switch typeStr {
	case "string":
		if isField {
			return "*string"
		}
		return "string"
	case "boolean":
		if isField {
			return "*bool"
		}
		return "bool"
	case "number":
		if isField {
			return "*float64"
		}
		return "float64"
	case "integer":
		if isField {
			return "*int64"
		}
		return "int64"
	case "array":
		if prop.Items != nil {
			itemType := getGoType(prop.Items, false)
			return "[]" + itemType
		}
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func generateModel(schema *Schema, path string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	sb.WriteString("package fhir\n\n")

	var keys []string
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		def := schema.Defs[k]
		sb.WriteString(fmt.Sprintf("// %s\n", k))
		sb.WriteString(fmt.Sprintf("type %s struct {\n", k))

		var propKeys []string
		for pk := range def.Properties {
			propKeys = append(propKeys, pk)
		}
		sort.Strings(propKeys)

		for _, pk := range propKeys {
			prop := def.Properties[pk]
			required := isRequired(def, pk)
			goType := getGoType(prop, true)
			goName := toGoName(pk)

			jsonTag := pk
			if !required {
				jsonTag += ",omitempty"
			}

			// gqlgen uses this explicit tag to preserve FHIR primitive-extension
			// names such as _birthDate, whose Go field is XBirthDate. Keeping
			// the tag on every field makes autobinding deterministic while the
			// JSON tag remains the storage contract.
			sb.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\" gqlgen:\"%s\"`\n", goName, goType, jsonTag, pk))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
