package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

func generateFHIRResources(schema *Schema, resourcesPath, graphqlPath string) error {
	roots := schemaFHIRRootResourceTypes(schema)
	if len(roots) == 0 {
		return fmt.Errorf("FHIR schema has no concrete resource definitions")
	}

	var resources strings.Builder
	resources.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	resources.WriteString("package fhir\n\n")
	resources.WriteString("type ConcreteResource interface {\n\tGetID() string\n\tGetResourceType() string\n}\n\n")
	resources.WriteString("func NewConcreteResource(resourceType string) (ConcreteResource, bool) {\n\tvar value ConcreteResource\n\tswitch resourceType {\n")
	for _, root := range roots {
		fmt.Fprintf(&resources, "\tcase %q:\n\t\tvalue = &%s{}\n", root, root)
	}
	resources.WriteString("\tdefault:\n\t\treturn nil, false\n\t}\n\treturn value, true\n}\n\n")
	resources.WriteString("func fhirID(value *string) string {\n\tif value == nil {\n\t\treturn \"\"\n\t}\n\treturn *value\n}\n\n")
	resources.WriteString("func fhirType(value *string, fallback string) string {\n\tif value == nil || *value == \"\" {\n\t\treturn fallback\n\t}\n\treturn *value\n}\n\n")
	for _, root := range roots {
		fmt.Fprintf(&resources, "func (x %s) GetID() string { return fhirID(x.ID) }\n", root)
		fmt.Fprintf(&resources, "func (x %s) GetResourceType() string { return fhirType(x.ResourceType, %q) }\n", root, root)
	}
	if err := writeGeneratedGo(resourcesPath, resources.String()); err != nil {
		return err
	}

	var graphql strings.Builder
	graphql.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	graphql.WriteString("package fhir\n\n")
	for _, root := range roots {
		fmt.Fprintf(&graphql, "func (x %s) IsFHIRResource() {}\n", root)
	}
	return writeGeneratedGo(graphqlPath, graphql.String())
}

func writeGeneratedGo(path, source string) error {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0644)
}
