package main

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func generateValidate(schema *Schema, path string) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/generate/main.go. DO NOT EDIT.\n")
	sb.WriteString("package fhir\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"regexp\"\n")
	sb.WriteString("\t\"unicode/utf8\"\n")
	sb.WriteString(")\n\n")

	var keys []string
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Collect and write regexes
	sb.WriteString("// Pre-compiled regular expressions for pattern validation\n")
	sb.WriteString("var (\n")
	regexMap := make(map[string]string)
	for _, k := range keys {
		def := schema.Defs[k]
		var propKeys []string
		for pk := range def.Properties {
			propKeys = append(propKeys, pk)
		}
		sort.Strings(propKeys)

		for _, pk := range propKeys {
			prop := def.Properties[pk]
			if prop.Pattern != "" && prop.Pattern != "[ \\r\\n\\t\\S]+" && prop.Pattern != "\\S*" {
				varName := fmt.Sprintf("rx_%s_%s", k, toGoName(pk))
				regexMap[varName] = prop.Pattern
				sb.WriteString(fmt.Sprintf("\t%s = regexp.MustCompile(%s)\n", varName, strconv.Quote(prop.Pattern)))
			}
			// check array items pattern
			if prop.Items != nil && prop.Items.Pattern != "" && prop.Items.Pattern != "[ \\r\\n\\t\\S]+" && prop.Items.Pattern != "\\S*" {
				varName := fmt.Sprintf("rx_%s_%s_items", k, toGoName(pk))
				regexMap[varName] = prop.Items.Pattern
				sb.WriteString(fmt.Sprintf("\t%s = regexp.MustCompile(%s)\n", varName, strconv.Quote(prop.Items.Pattern)))
			}
		}
	}
	sb.WriteString(")\n\n")

	for _, k := range keys {
		def := schema.Defs[k]
		sb.WriteString(fmt.Sprintf("// Validate validates a %s struct against its schema constraints.\n", k))
		sb.WriteString(fmt.Sprintf("func (x *%s) Validate() error {\n", k))
		sb.WriteString("\tif x == nil {\n\t\treturn nil\n\t}\n")

		var propKeys []string
		for pk := range def.Properties {
			propKeys = append(propKeys, pk)
		}
		sort.Strings(propKeys)

		for _, pk := range propKeys {
			prop := def.Properties[pk]
			required := isRequired(def, pk)
			goName := "x." + toGoName(pk)

			// 1. Required field check
			if required {
				sb.WriteString(fmt.Sprintf("\tif %s == nil {\n", goName))
				sb.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"required field '%s' is missing\")\n", pk))
				sb.WriteString("\t}\n")
			}

			// Under what condition do we validate constraints?
			// For optional fields: if not nil.
			// For required fields: since they are pointers (or strings/bools if required), we check if they are not nil.
			// Actually, if we made a required field non-pointer (like string), we can check it directly.
			// Let's determine if goType is pointer.
			goType := getGoType(prop, true)
			isPointer := strings.HasPrefix(goType, "*")
			isSlice := strings.HasPrefix(goType, "[]")
			isCustomComments := goType == "FHIRComments"

			if isCustomComments {
				// No validation needed for FHIRComments
				continue
			}

			indent := "\t"
			if isPointer {
				sb.WriteString(fmt.Sprintf("\tif %s != nil {\n", goName))
				indent = "\t\t"
			} else if isSlice {
				sb.WriteString(fmt.Sprintf("\tif %s != nil {\n", goName))
				indent = "\t\t"
			}

			// Validate constraints on the field value
			valExpr := goName
			if isPointer {
				valExpr = "*" + goName
			}

			// 2. Const check
			if prop.Const != nil {
				constStr, ok := prop.Const.(string)
				if ok {
					sb.WriteString(fmt.Sprintf("%sif %s != %s {\n", indent, valExpr, strconv.Quote(constStr)))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' must be exactly '%s'\")\n", indent, pk, constStr))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				}
			}

			// 3. Pattern check
			if prop.Pattern != "" {
				if prop.Pattern == "[ \\r\\n\\t\\S]+" {
					sb.WriteString(fmt.Sprintf("%sif %s == \"\" {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' does not match pattern '%s'\")\n", indent, pk, escapePattern(prop.Pattern)))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				} else if prop.Pattern == "\\S*" {
					// Skip unanchored \S* check since it always matches
				} else {
					varName := fmt.Sprintf("rx_%s_%s", k, toGoName(pk))
					sb.WriteString(fmt.Sprintf("%sif !%s.MatchString(%s) {\n", indent, varName, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' does not match pattern '%s'\")\n", indent, pk, escapePattern(prop.Pattern)))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				}
			}

			// 4. MinLength check
			if prop.MinLength != nil {
				sb.WriteString(fmt.Sprintf("%sif utf8.RuneCountInString(%s) < %d {\n", indent, valExpr, *prop.MinLength))
				sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' is too short (min %d characters)\")\n", indent, pk, *prop.MinLength))
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			}

			// 5. MaxLength check
			if prop.MaxLength != nil {
				sb.WriteString(fmt.Sprintf("%sif utf8.RuneCountInString(%s) > %d {\n", indent, valExpr, *prop.MaxLength))
				sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' is too long (max %d characters)\")\n", indent, pk, *prop.MaxLength))
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			}

			// 6. Minimum check
			if prop.Minimum != nil {
				sb.WriteString(fmt.Sprintf("%sif %s < %f {\n", indent, valExpr, *prop.Minimum))
				sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' is below minimum %f\")\n", indent, pk, *prop.Minimum))
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			}

			// 7. ExclusiveMinimum check
			if prop.ExclusiveMinimum != nil {
				sb.WriteString(fmt.Sprintf("%sif %s <= %f {\n", indent, valExpr, *prop.ExclusiveMinimum))
				sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' is below exclusive minimum %f\")\n", indent, pk, *prop.ExclusiveMinimum))
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			}

			// 8. Format check
			if prop.Format != "" {
				switch prop.Format {
				case "date-time":
					sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirDateTime(%s); err != nil {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' has invalid date-time format: %%w\", err)\n", indent, pk))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				case "date":
					sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirDate(%s); err != nil {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' has invalid date format: %%w\", err)\n", indent, pk))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				case "time":
					sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirTime(%s); err != nil {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' has invalid time format: %%w\", err)\n", indent, pk))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				case "uri":
					sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirURI(%s); err != nil {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' has invalid URI format: %%w\", err)\n", indent, pk))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				case "uuid":
					sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirUUID(%s); err != nil {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' has invalid UUID format: %%w\", err)\n", indent, pk))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				case "binary":
					sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirBinary(%s); err != nil {\n", indent, valExpr))
					sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' has invalid binary format: %%w\", err)\n", indent, pk))
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				}
			}

			// 9. Nested validation (Struct pointer)
			if prop.Ref != "" && refName(prop.Ref) != "links" {
				sb.WriteString(fmt.Sprintf("%sif err := %s.Validate(); err != nil {\n", indent, goName))
				sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s' is invalid: %%w\", err)\n", indent, pk))
				sb.WriteString(fmt.Sprintf("%s}\n", indent))
			}

			// 10. Slice item validation
			if isSlice && prop.Items != nil {
				hasItemValidation := (prop.Items.Pattern != "" && prop.Items.Pattern != "\\S*") || prop.Items.Format != "" || (prop.Items.Ref != "" && refName(prop.Items.Ref) != "links")
				if hasItemValidation {
					itemName := "item"
					sb.WriteString(fmt.Sprintf("%sfor i, %s := range %s {\n", indent, itemName, valExpr))
					loopIndent := indent + "\t"

					itemValExpr := itemName
					itemIsPointer := strings.HasPrefix(getGoType(prop.Items, false), "*")
					if itemIsPointer {
						sb.WriteString(fmt.Sprintf("%sif %s != nil {\n", loopIndent, itemName))
						loopIndent += "\t"
						itemValExpr = "*" + itemName
					}

					// Check items constraints
					if prop.Items.Pattern != "" {
						if prop.Items.Pattern == "[ \\r\\n\\t\\S]+" {
							sb.WriteString(fmt.Sprintf("%sif %s == \"\" {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' does not match pattern '%s'\", i)\n", loopIndent, pk, escapePattern(prop.Items.Pattern)))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						} else if prop.Items.Pattern == "\\S*" {
							// Skip unanchored \S* check
						} else {
							varName := fmt.Sprintf("rx_%s_%s_items", k, toGoName(pk))
							sb.WriteString(fmt.Sprintf("%sif !%s.MatchString(%s) {\n", loopIndent, varName, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' does not match pattern '%s'\", i)\n", loopIndent, pk, escapePattern(prop.Items.Pattern)))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						}
					}
					if prop.Items.Format != "" {
						switch prop.Items.Format {
						case "date-time":
							sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirDateTime(%s); err != nil {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' has invalid date-time format: %%w\", i, err)\n", loopIndent, pk))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						case "date":
							sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirDate(%s); err != nil {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' has invalid date format: %%w\", i, err)\n", loopIndent, pk))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						case "time":
							sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirTime(%s); err != nil {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' has invalid time format: %%w\", i, err)\n", loopIndent, pk))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						case "uri":
							sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirURI(%s); err != nil {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' has invalid URI format: %%w\", i, err)\n", loopIndent, pk))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						case "uuid":
							sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirUUID(%s); err != nil {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' has invalid UUID format: %%w\", i, err)\n", loopIndent, pk))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						case "binary":
							sb.WriteString(fmt.Sprintf("%sif err := ValidateFhirBinary(%s); err != nil {\n", loopIndent, itemValExpr))
							sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' has invalid binary format: %%w\", i, err)\n", loopIndent, pk))
							sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
						}
					}

					// Check nested object validation for slice item
					if prop.Items.Ref != "" && refName(prop.Items.Ref) != "links" {
						sb.WriteString(fmt.Sprintf("%sif err := %s.Validate(); err != nil {\n", loopIndent, itemName))
						sb.WriteString(fmt.Sprintf("%s\treturn fmt.Errorf(\"field '%s[%%d]' is invalid: %%w\", i, err)\n", loopIndent, pk))
						sb.WriteString(fmt.Sprintf("%s}\n", loopIndent))
					}

					if itemIsPointer {
						sb.WriteString(fmt.Sprintf("%s}\n", indent+"\t"))
					}
					sb.WriteString(fmt.Sprintf("%s}\n", indent))
				}
			}

			if isPointer || isSlice {
				sb.WriteString("\t}\n")
			}
		}

		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

func escapePattern(pat string) string {
	s := strings.ReplaceAll(pat, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}
