package dataframe

func buildGDCCaseAssayMatrixAdvancedBuilder(project string, authResourcePaths []string) Builder {
	return Builder{
		Project:           project,
		AuthResourcePaths: cloneStrings(authResourcePaths),
		RootResourceType:  "Patient",
		PlanHint: &PlanHint{
			Mode:                    "advanced_lowered",
			Profile:                 "gdc_case_assay_matrix_fixture",
			NamedSetCount:           12,
			ClassifiedFileSummaries: true,
		},
		Sets: []NamedSet{
			{Name: "patient_neighbors", Kind: SetKindTraverse, Label: "subject_Patient", Unique: true},
			{Name: "specimens", Kind: SetKindFilter, Source: "patient_neighbors", MatchResourceType: "Specimen", SortField: "_key"},
			{Name: "groups", Kind: SetKindTraverse, Source: "specimens", Label: "member_entity_Specimen", ToResourceType: "Group", Unique: true},
			{Name: "direct_files", Kind: SetKindTraverse, Source: "specimens", Label: "subject_Specimen", ToResourceType: "DocumentReference"},
			{Name: "grouped_files", Kind: SetKindTraverse, Source: "groups", Label: "subject_Group", ToResourceType: "DocumentReference"},
			{Name: "patient_files", Kind: SetKindFilter, Source: "patient_neighbors", MatchResourceType: "DocumentReference"},
			{Name: "files", Kind: SetKindUnion, Sources: []string{"direct_files", "grouped_files", "patient_files"}},
			{Name: "file_summaries", Kind: SetKindClassifyDocumentReference, Source: "files"},
			{Name: "conditions", Kind: SetKindFilter, Source: "patient_neighbors", MatchResourceType: "Condition", SortField: "_key"},
			{Name: "research_subjects", Kind: SetKindFilter, Source: "patient_neighbors", MatchResourceType: "ResearchSubject", SortField: "_key"},
			{Name: "study_payloads", Kind: SetKindLookupStudy, Source: "research_subjects"},
			{Name: "treatments", Kind: SetKindFilter, Source: "patient_neighbors", MatchResourceType: "MedicationAdministration"},
		},
		DerivedFields: []DerivedField{
			{Name: "project", Operation: DerivedOpRootField, Select: "project"},
			{Name: "recipe", Operation: DerivedOpConst, ConstValue: "gdc_case_assay_matrix"},
			{Name: "case_fhir_id", Source: "root", Operation: DerivedOpFirstNonNull, Select: "id"},
			{Name: "case_id", Source: "root", Operation: DerivedOpFirstNonNull, Select: `identifier[].value where system contains "case_id"`},
			{Name: "case_submitter_id", Source: "root", Operation: DerivedOpFirstNonNull, Select: `identifier[].value where system contains "case_submitter_id"`},
			{Name: "gender", Source: "root", Operation: DerivedOpFirstNonNull, Select: "gender"},
			{Name: "deceased", Source: "root", Operation: DerivedOpFirstNonNull, Select: "deceasedBoolean"},
			{Name: "birth_sex", Source: "root", Operation: DerivedOpFirstNonNull, Select: `extension[].valueCode where url contains "us-core-birthsex"`, FallbackSelects: []string{`extension[].valueString where url contains "us-core-birthsex"`}},
			{Name: "race", Source: "root", Operation: DerivedOpFirstNonNull, Select: `extension[].valueString where url contains "us-core-race"`, FallbackSelects: []string{`extension[].valueCode where url contains "us-core-race"`}},
			{Name: "ethnicity", Source: "root", Operation: DerivedOpFirstNonNull, Select: `extension[].valueString where url contains "us-core-ethnicity"`, FallbackSelects: []string{`extension[].valueCode where url contains "us-core-ethnicity"`}},
			{Name: "patient_age", Source: "root", Operation: DerivedOpFirstNonNull, Select: `extension[].valueQuantity.value where url contains "Patient-age"`},
			{Name: "diagnosis_count", Source: "conditions", Operation: DerivedOpCount},
			{Name: "diagnosis_id", Source: "conditions", Operation: DerivedOpFirstNonNull, Select: `identifier[].value where system contains "diagnosis_id"`},
			{Name: "primary_diagnosis", Source: "conditions", Operation: DerivedOpFirstNonNull, Select: `code.coding[].display where system contains "primary_diagnosis"`, FallbackSelects: []string{`code.coding[].display`, `code.coding[].code`}},
			{Name: "diagnosis_body_site", Source: "conditions", Operation: DerivedOpFirstNonNull, Select: `bodySite[].coding[].display`, FallbackSelects: []string{`bodySite[].coding[].code`}},
			{Name: "research_subject_id", Source: "research_subjects", Operation: DerivedOpFirstNonNull, Select: "id"},
			{Name: "research_subject_status", Source: "research_subjects", Operation: DerivedOpFirstNonNull, Select: "status"},
			{Name: "study_id", Source: "study_payloads", Operation: DerivedOpFirstNonNull, Select: "id"},
			{Name: "study_identifier", Source: "study_payloads", Operation: DerivedOpFirstNonNull, Select: "identifier[].value"},
			{Name: "study_name", Source: "study_payloads", Operation: DerivedOpFirstNonNull, Select: "name"},
			{Name: "study_title", Source: "study_payloads", Operation: DerivedOpFirstNonNull, Select: "title"},
			{Name: "specimen_count", Source: "specimens", Operation: DerivedOpCount},
			{Name: "specimen_types", Source: "specimens", Operation: DerivedOpUnique, Select: `type.coding[].display`, FallbackSelects: []string{`type.coding[].code`}},
			{Name: "preservation_methods", Source: "specimens", Operation: DerivedOpUnique, Select: `processing[].method.coding[].display where system contains "preservation_method"`, FallbackSelects: []string{`processing[].method.coding[].code where system contains "preservation_method"`}},
			{Name: "file_count", Source: "file_summaries", Operation: DerivedOpCount},
			{Name: "data_categories", Source: "file_summaries", Operation: DerivedOpUnique, Select: "data_category"},
			{Name: "data_types", Source: "file_summaries", Operation: DerivedOpUnique, Select: "data_type"},
			{Name: "experimental_strategies", Source: "file_summaries", Operation: DerivedOpUnique, Select: "experimental_strategy"},
			{Name: "workflow_types", Source: "file_summaries", Operation: DerivedOpUnique, Select: "workflow_type"},
			{Name: "has_snv", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_snv"},
			{Name: "snv_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_snv"},
			{Name: "annotated_somatic_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_annotated_somatic"},
			{Name: "raw_somatic_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_raw_somatic"},
			{Name: "has_wxs", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_wxs"},
			{Name: "has_wgs", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_wgs"},
			{Name: "has_rnaseq", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_rnaseq"},
			{Name: "has_expression", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_expression"},
			{Name: "expression_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_expression"},
			{Name: "has_fusion", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_fusion"},
			{Name: "fusion_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_fusion"},
			{Name: "has_cnv", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_cnv"},
			{Name: "cnv_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_cnv"},
			{Name: "has_methylation", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_methylation"},
			{Name: "methylation_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_methylation"},
			{Name: "has_slide", Source: "file_summaries", Operation: DerivedOpAny, Predicate: "is_slide"},
			{Name: "slide_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_slide"},
			{Name: "aligned_read_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_aligned_reads"},
			{Name: "clinical_file_count", Source: "file_summaries", Operation: DerivedOpCountWhere, Predicate: "is_clinical"},
			{Name: "treatment_count", Source: "treatments", Operation: DerivedOpCount},
			{Name: "treatment_categories", Source: "treatments", Operation: DerivedOpUnique, Select: `category[].coding[].display`, FallbackSelects: []string{`category[].coding[].code`}},
		},
		RepresentativeSlices: []RepresentativeSlice{
			{Name: "representative_snv_files", SourceSet: "file_summaries", Predicate: "is_snv", Limit: 5},
			{Name: "representative_expression_files", SourceSet: "file_summaries", Predicate: "is_expression", Limit: 5},
			{Name: "representative_cnv_files", SourceSet: "file_summaries", Predicate: "is_cnv", Limit: 5},
			{Name: "representative_methylation_files", SourceSet: "file_summaries", Predicate: "is_methylation", Limit: 5},
			{Name: "representative_slide_files", SourceSet: "file_summaries", Predicate: "is_slide", Limit: 5},
		},
	}
}
