package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"arangodb-proto/internal/dataframe"
	"arangodb-proto/internal/graphqlapi/model"
	"context"
)

// RunFhirDataframe is the resolver for the runFhirDataframe field.
func (r *mutationResolver) RunFhirDataframe(ctx context.Context, input model.FhirDataframeInput, mode model.DataframeRunMode, previewLimit *int) (*model.FhirDataframeRunResult, error) {
	limit := 0
	if previewLimit != nil {
		limit = *previewLimit
	} else if input.Limit != nil {
		limit = *input.Limit
	}
	result, err := r.Service.RunDataframe(ctx, dataframe.RunRequest{
		Builder:      builderFromInput(input),
		Mode:         mode.String(),
		PreviewLimit: limit,
	})
	if err != nil {
		return nil, err
	}
	out := &model.FhirDataframeRunResult{
		Mode: model.DataframeRunMode(result.Mode),
	}
	if result.Preview != nil {
		out.Preview = &model.FhirDataframePreview{
			Columns:  cloneStrings(result.Preview.Columns),
			Rows:     graphqlRows(result.Preview.Rows),
			RowCount: result.Preview.RowCount,
		}
	}
	if result.Export != nil {
		out.Export = &model.FhirDataframeExportHandle{
			ExportID: result.Export.ExportID,
			Status:   result.Export.Status,
			Format:   result.Export.Format,
		}
	}
	return out, nil
}

// DataframeBuilderIntrospection is the resolver for the dataframeBuilderIntrospection field.
func (r *queryResolver) DataframeBuilderIntrospection(ctx context.Context, input model.DataframeBuilderIntrospectionInput) (*model.DataframeBuilderIntrospection, error) {
	includePivotOnlyFields := true
	if input.IncludePivotOnlyFields != nil {
		includePivotOnlyFields = *input.IncludePivotOnlyFields
	}
	resp, err := r.Service.Introspect(ctx, IntrospectionRequest{
		Project:                input.Project,
		RootResourceType:       input.RootResourceType,
		AuthResourcePaths:      input.AuthResourcePaths,
		IncludePivotOnlyFields: includePivotOnlyFields,
	})
	if err != nil {
		return nil, err
	}
	return &model.DataframeBuilderIntrospection{
		Project:           resp.Project,
		RootResourceType:  resp.RootResourceType,
		AuthResourcePaths: append([]string(nil), resp.AuthResourcePaths...),
		Root:              resourceHints(resp.Root),
		RelatedResources:  relatedResourceHints(resp.RelatedResources),
		Traversals:        traversalHints(resp.Traversals),
		Fields:            fieldHints(resp.Fields),
		PivotFields:       fieldHints(resp.PivotFields),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *fhirDataframePreviewResolver) Rows(ctx context.Context, obj *model.FhirDataframePreview) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: Rows - rows"))
}
func (r *Resolver) FhirDataframePreview() FhirDataframePreviewResolver {
	return &fhirDataframePreviewResolver{r}
}
type fhirDataframePreviewResolver struct{ *Resolver }
*/
