// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type DataframeBuilderIntrospection struct {
	Project           string                           `json:"project"`
	RootResourceType  string                           `json:"rootResourceType"`
	AuthResourcePaths []string                         `json:"authResourcePaths"`
	Root              *DataframeResourceHints          `json:"root"`
	RelatedResources  []*DataframeRelatedResourceHints `json:"relatedResources"`
	Traversals        []*DataframeTraversalHint        `json:"traversals"`
	Fields            []*DataframeFieldHint            `json:"fields"`
	PivotFields       []*DataframeFieldHint            `json:"pivotFields"`
}

type DataframeBuilderIntrospectionInput struct {
	Project                string   `json:"project"`
	RootResourceType       string   `json:"rootResourceType"`
	AuthResourcePaths      []string `json:"authResourcePaths,omitempty"`
	IncludePivotOnlyFields *bool    `json:"includePivotOnlyFields,omitempty"`
}

type DataframeFieldHint struct {
	ResourceType      string   `json:"resourceType"`
	Path              string   `json:"path"`
	Selector          string   `json:"selector"`
	Kind              string   `json:"kind"`
	DocCount          int      `json:"docCount"`
	SampleCount       int      `json:"sampleCount"`
	DistinctValues    []string `json:"distinctValues"`
	DistinctTruncated bool     `json:"distinctTruncated"`
	PivotCandidate    bool     `json:"pivotCandidate"`
	PivotKind         *string  `json:"pivotKind,omitempty"`
	PivotColumns      []string `json:"pivotColumns"`
}

type DataframeRelatedResourceHints struct {
	ViaLabel  string                  `json:"viaLabel"`
	EdgeCount int                     `json:"edgeCount"`
	Target    *DataframeResourceHints `json:"target"`
}

type DataframeResourceHints struct {
	ResourceType string                    `json:"resourceType"`
	Fields       []*DataframeFieldHint     `json:"fields"`
	PivotFields  []*DataframeFieldHint     `json:"pivotFields"`
	Traversals   []*DataframeTraversalHint `json:"traversals"`
}

type DataframeTraversalHint struct {
	FromType  string `json:"fromType"`
	Label     string `json:"label"`
	ToType    string `json:"toType"`
	EdgeCount int    `json:"edgeCount"`
}

type FhirDataframeExportHandle struct {
	ExportID string `json:"exportId"`
	Status   string `json:"status"`
	Format   string `json:"format"`
}

type FhirDataframeInput struct {
	Project           string                    `json:"project"`
	AuthResourcePath  *string                   `json:"authResourcePath,omitempty"`
	AuthResourcePaths []string                  `json:"authResourcePaths,omitempty"`
	RootResourceType  string                    `json:"rootResourceType"`
	RootFields        []*FhirFieldSelectInput   `json:"rootFields,omitempty"`
	RootPivots        []*FhirPivotInput         `json:"rootPivots,omitempty"`
	Traverse          []*FhirTraversalStepInput `json:"traverse,omitempty"`
	Limit             *int                      `json:"limit,omitempty"`
	Cursor            *string                   `json:"cursor,omitempty"`
}

type FhirDataframePreview struct {
	Columns  []string            `json:"columns"`
	Rows     []*FhirDataframeRow `json:"rows"`
	RowCount int                 `json:"rowCount"`
}

type FhirDataframeRow struct {
	Data map[string]interface{} `json:"data"`
}

type FhirDataframeRunResult struct {
	Mode    DataframeRunMode           `json:"mode"`
	Preview *FhirDataframePreview      `json:"preview,omitempty"`
	Export  *FhirDataframeExportHandle `json:"export,omitempty"`
}

type FhirFieldSelectInput struct {
	Name          string        `json:"name"`
	FhirPath      string        `json:"fhirPath"`
	SelectionHint *string       `json:"selectionHint,omitempty"`
	ValueMode     FhirValueMode `json:"valueMode"`
}

type FhirPivotInput struct {
	Name            string         `json:"name"`
	FhirPath        string         `json:"fhirPath"`
	PivotKind       *FhirPivotKind `json:"pivotKind,omitempty"`
	SelectedColumns []string       `json:"selectedColumns"`
	ValuePath       *string        `json:"valuePath,omitempty"`
}

type FhirTraversalStepInput struct {
	EdgeLabel      string                    `json:"edgeLabel"`
	ToResourceType string                    `json:"toResourceType"`
	Alias          string                    `json:"alias"`
	Fields         []*FhirFieldSelectInput   `json:"fields"`
	Pivots         []*FhirPivotInput         `json:"pivots,omitempty"`
	Traverse       []*FhirTraversalStepInput `json:"traverse,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type DataframeRunMode string

const (
	DataframeRunModePreview DataframeRunMode = "PREVIEW"
	DataframeRunModeExport  DataframeRunMode = "EXPORT"
)

var AllDataframeRunMode = []DataframeRunMode{
	DataframeRunModePreview,
	DataframeRunModeExport,
}

func (e DataframeRunMode) IsValid() bool {
	switch e {
	case DataframeRunModePreview, DataframeRunModeExport:
		return true
	}
	return false
}

func (e DataframeRunMode) String() string {
	return string(e)
}

func (e *DataframeRunMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DataframeRunMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DataframeRunMode", str)
	}
	return nil
}

func (e DataframeRunMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FhirPivotKind string

const (
	FhirPivotKindCodeableConceptDisplayValue FhirPivotKind = "CODEABLE_CONCEPT_DISPLAY_VALUE"
)

var AllFhirPivotKind = []FhirPivotKind{
	FhirPivotKindCodeableConceptDisplayValue,
}

func (e FhirPivotKind) IsValid() bool {
	switch e {
	case FhirPivotKindCodeableConceptDisplayValue:
		return true
	}
	return false
}

func (e FhirPivotKind) String() string {
	return string(e)
}

func (e *FhirPivotKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FhirPivotKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FhirPivotKind", str)
	}
	return nil
}

func (e FhirPivotKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FhirValueMode string

const (
	FhirValueModeAuto     FhirValueMode = "AUTO"
	FhirValueModeFirst    FhirValueMode = "FIRST"
	FhirValueModeAll      FhirValueMode = "ALL"
	FhirValueModeDistinct FhirValueMode = "DISTINCT"
)

var AllFhirValueMode = []FhirValueMode{
	FhirValueModeAuto,
	FhirValueModeFirst,
	FhirValueModeAll,
	FhirValueModeDistinct,
}

func (e FhirValueMode) IsValid() bool {
	switch e {
	case FhirValueModeAuto, FhirValueModeFirst, FhirValueModeAll, FhirValueModeDistinct:
		return true
	}
	return false
}

func (e FhirValueMode) String() string {
	return string(e)
}

func (e *FhirValueMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FhirValueMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FhirValueMode", str)
	}
	return nil
}

func (e FhirValueMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
