// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
)

type DataframeBuilderIntrospection struct {
	Project           string                           `json:"project"`
	RootResourceType  string                           `json:"rootResourceType"`
	AuthResourcePaths []string                         `json:"authResourcePaths"`
	Root              *DataframeResourceHints          `json:"root"`
	RelatedResources  []*DataframeRelatedResourceHints `json:"relatedResources"`
	Traversals        []*DataframeTraversalHint        `json:"traversals"`
	Fields            []*DataframeFieldHint            `json:"fields"`
	PivotFields       []*DataframeFieldHint            `json:"pivotFields"`
}

type DataframeBuilderIntrospectionInput struct {
	Project                string   `json:"project"`
	RootResourceType       string   `json:"rootResourceType"`
	AuthResourcePaths      []string `json:"authResourcePaths,omitempty"`
	IncludePivotOnlyFields *bool    `json:"includePivotOnlyFields,omitempty"`
}

type DataframeFieldHint struct {
	ResourceType               string                  `json:"resourceType"`
	FieldRef                   string                  `json:"fieldRef"`
	Label                      string                  `json:"label"`
	Path                       string                  `json:"path"`
	Selector                   *DataframeFieldSelector `json:"selector"`
	Kind                       string                  `json:"kind"`
	DocCount                   int                     `json:"docCount"`
	SampleCount                int                     `json:"sampleCount"`
	DistinctValues             []string                `json:"distinctValues"`
	DistinctTruncated          bool                    `json:"distinctTruncated"`
	PivotCandidate             bool                    `json:"pivotCandidate"`
	PivotKind                  *string                 `json:"pivotKind,omitempty"`
	PivotColumns               []string                `json:"pivotColumns"`
	PivotFamily                *FhirPivotFamily        `json:"pivotFamily,omitempty"`
	DefaultPivotColumnSelector *DataframeFieldSelector `json:"defaultPivotColumnSelector,omitempty"`
	DefaultPivotValueSelector  *DataframeFieldSelector `json:"defaultPivotValueSelector,omitempty"`
}

type DataframeFieldPredicate struct {
	Path  string                      `json:"path"`
	Op    FhirFieldPredicateOperation `json:"op"`
	Value string                      `json:"value"`
}

type DataframeFieldSelector struct {
	SourcePath *string                  `json:"sourcePath,omitempty"`
	Where      *DataframeFieldPredicate `json:"where,omitempty"`
	ValuePath  string                   `json:"valuePath"`
}

type DataframeRelatedResourceHints struct {
	ViaLabel  string                  `json:"viaLabel"`
	EdgeCount int                     `json:"edgeCount"`
	Target    *DataframeResourceHints `json:"target"`
}

type DataframeResourceHints struct {
	ResourceType string                    `json:"resourceType"`
	Fields       []*DataframeFieldHint     `json:"fields"`
	PivotFields  []*DataframeFieldHint     `json:"pivotFields"`
	Traversals   []*DataframeTraversalHint `json:"traversals"`
}

type DataframeTraversalHint struct {
	FromType  string `json:"fromType"`
	Label     string `json:"label"`
	ToType    string `json:"toType"`
	EdgeCount int    `json:"edgeCount"`
}

type FhirAggregateInput struct {
	Name              string                 `json:"name"`
	Operation         FhirAggregateOperation `json:"operation"`
	FieldRef          *string                `json:"fieldRef,omitempty"`
	FhirPath          *string                `json:"fhirPath,omitempty"`
	PredicateFieldRef *string                `json:"predicateFieldRef,omitempty"`
	PredicatePath     *string                `json:"predicatePath,omitempty"`
	PredicateEquals   *string                `json:"predicateEquals,omitempty"`
	ValueMode         FhirValueMode          `json:"valueMode"`
}

type FhirDataframeInput struct {
	Project           string                          `json:"project"`
	AuthResourcePath  *string                         `json:"authResourcePath,omitempty"`
	AuthResourcePaths []string                        `json:"authResourcePaths,omitempty"`
	RootResourceType  string                          `json:"rootResourceType"`
	RootFields        []*FhirFieldSelectInput         `json:"rootFields,omitempty"`
	RootPivots        []*FhirPivotInput               `json:"rootPivots,omitempty"`
	RootAggregates    []*FhirAggregateInput           `json:"rootAggregates,omitempty"`
	RootSlices        []*FhirRepresentativeSliceInput `json:"rootSlices,omitempty"`
	Traverse          []*FhirTraversalStepInput       `json:"traverse,omitempty"`
	Limit             *int                            `json:"limit,omitempty"`
	Cursor            *string                         `json:"cursor,omitempty"`
}

type FhirDataframeResult struct {
	Columns  []string        `json:"columns"`
	Rows     json.RawMessage `json:"rows"`
	RowCount int             `json:"rowCount"`
}

type FhirFieldPredicateInput struct {
	Path  string                      `json:"path"`
	Op    FhirFieldPredicateOperation `json:"op"`
	Value string                      `json:"value"`
}

type FhirFieldSelectInput struct {
	Name              string                    `json:"name"`
	FieldRef          *string                   `json:"fieldRef,omitempty"`
	Selector          *FhirFieldSelectorInput   `json:"selector,omitempty"`
	SelectionHint     *string                   `json:"selectionHint,omitempty"`
	FallbackFieldRefs []string                  `json:"fallbackFieldRefs"`
	FallbackSelectors []*FhirFieldSelectorInput `json:"fallbackSelectors"`
	ValueMode         FhirValueMode             `json:"valueMode"`
}

type FhirFieldSelectorInput struct {
	SourcePath *string                  `json:"sourcePath,omitempty"`
	Where      *FhirFieldPredicateInput `json:"where,omitempty"`
	ValuePath  string                   `json:"valuePath"`
}

type FhirPivotInput struct {
	Name           string                  `json:"name"`
	FieldRef       *string                 `json:"fieldRef,omitempty"`
	ColumnSelector *FhirFieldSelectorInput `json:"columnSelector,omitempty"`
	ValueSelector  *FhirFieldSelectorInput `json:"valueSelector,omitempty"`
	Columns        []string                `json:"columns"`
}

type FhirRepresentativeSliceInput struct {
	Name          string                  `json:"name"`
	Limit         int                     `json:"limit"`
	WhereFieldRef *string                 `json:"whereFieldRef,omitempty"`
	WherePath     *string                 `json:"wherePath,omitempty"`
	WhereEquals   *string                 `json:"whereEquals,omitempty"`
	Fields        []*FhirFieldSelectInput `json:"fields"`
}

type FhirTraversalStepInput struct {
	EdgeLabel      string                          `json:"edgeLabel"`
	ToResourceType string                          `json:"toResourceType"`
	Alias          string                          `json:"alias"`
	Fields         []*FhirFieldSelectInput         `json:"fields"`
	Pivots         []*FhirPivotInput               `json:"pivots,omitempty"`
	Aggregates     []*FhirAggregateInput           `json:"aggregates,omitempty"`
	Slices         []*FhirRepresentativeSliceInput `json:"slices,omitempty"`
	Traverse       []*FhirTraversalStepInput       `json:"traverse,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type FhirAggregateOperation string

const (
	FhirAggregateOperationCount          FhirAggregateOperation = "COUNT"
	FhirAggregateOperationCountDistinct  FhirAggregateOperation = "COUNT_DISTINCT"
	FhirAggregateOperationExists         FhirAggregateOperation = "EXISTS"
	FhirAggregateOperationDistinctValues FhirAggregateOperation = "DISTINCT_VALUES"
)

var AllFhirAggregateOperation = []FhirAggregateOperation{
	FhirAggregateOperationCount,
	FhirAggregateOperationCountDistinct,
	FhirAggregateOperationExists,
	FhirAggregateOperationDistinctValues,
}

func (e FhirAggregateOperation) IsValid() bool {
	switch e {
	case FhirAggregateOperationCount, FhirAggregateOperationCountDistinct, FhirAggregateOperationExists, FhirAggregateOperationDistinctValues:
		return true
	}
	return false
}

func (e FhirAggregateOperation) String() string {
	return string(e)
}

func (e *FhirAggregateOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FhirAggregateOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FhirAggregateOperation", str)
	}
	return nil
}

func (e FhirAggregateOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FhirFieldPredicateOperation string

const (
	FhirFieldPredicateOperationContains FhirFieldPredicateOperation = "CONTAINS"
)

var AllFhirFieldPredicateOperation = []FhirFieldPredicateOperation{
	FhirFieldPredicateOperationContains,
}

func (e FhirFieldPredicateOperation) IsValid() bool {
	switch e {
	case FhirFieldPredicateOperationContains:
		return true
	}
	return false
}

func (e FhirFieldPredicateOperation) String() string {
	return string(e)
}

func (e *FhirFieldPredicateOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FhirFieldPredicateOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FhirFieldPredicateOperation", str)
	}
	return nil
}

func (e FhirFieldPredicateOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FhirPivotFamily string

const (
	FhirPivotFamilyCodeableConcept      FhirPivotFamily = "CODEABLE_CONCEPT"
	FhirPivotFamilyObservationCodeValue FhirPivotFamily = "OBSERVATION_CODE_VALUE"
)

var AllFhirPivotFamily = []FhirPivotFamily{
	FhirPivotFamilyCodeableConcept,
	FhirPivotFamilyObservationCodeValue,
}

func (e FhirPivotFamily) IsValid() bool {
	switch e {
	case FhirPivotFamilyCodeableConcept, FhirPivotFamilyObservationCodeValue:
		return true
	}
	return false
}

func (e FhirPivotFamily) String() string {
	return string(e)
}

func (e *FhirPivotFamily) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FhirPivotFamily(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FhirPivotFamily", str)
	}
	return nil
}

func (e FhirPivotFamily) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FhirValueMode string

const (
	FhirValueModeAuto     FhirValueMode = "AUTO"
	FhirValueModeFirst    FhirValueMode = "FIRST"
	FhirValueModeAll      FhirValueMode = "ALL"
	FhirValueModeDistinct FhirValueMode = "DISTINCT"
)

var AllFhirValueMode = []FhirValueMode{
	FhirValueModeAuto,
	FhirValueModeFirst,
	FhirValueModeAll,
	FhirValueModeDistinct,
}

func (e FhirValueMode) IsValid() bool {
	switch e {
	case FhirValueModeAuto, FhirValueModeFirst, FhirValueModeAll, FhirValueModeDistinct:
		return true
	}
	return false
}

func (e FhirValueMode) String() string {
	return string(e)
}

func (e *FhirValueMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FhirValueMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FhirValueMode", str)
	}
	return nil
}

func (e FhirValueMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
